DECLARE 
    REC_EMP EMP%ROWTYPE; -- REC_EMP테이블에 EMP의 모든 ROW 형태를 참조함
    V_EMPNO EMP.EMPNO%TYPE; -- V_EMPNO 변수는 EMP의 EMPNO를 참조함

BEGIN
    SELECT * INTO REC_EMP FROM EMP WHERE EMPNO = 7369; -- SELECT한 데이터를 REC_EMP 테이블에 집어 넣음 (반드시 SELECT * INTO)
    
    DBMS_OUTPUT.PUT_LINE('EMPNO => ' || REC_EMP.EMPNO);
    DBMS_OUTPUT.PUT_LINE('EMAME => ' || REC_EMP.ENAME);
    DBMS_OUTPUT.PUT_LINE('JOB => ' || REC_EMP.JOB);
    DBMS_OUTPUT.PUT_LINE('MGR => ' || REC_EMP.MGR);
    DBMS_OUTPUT.PUT_LINE('HIREDATE => ' || REC_EMP.HIREDATE);
    DBMS_OUTPUT.PUT_LINE('SAL => ' || REC_EMP.SAL);
    
    SELECT EMPNO, ENAME INTO V_EMPNO, REC_EMP.ENAME FROM EMP WHERE EMPNO = 7369;
    
    DBMS_OUTPUT.PUT_LINE('-------------------------');
    DBMS_OUTPUT.PUT_LINE('EMPNO => ' || V_EMPNO);
    DBMS_OUTPUT.PUT_LINE('EMPNO => ' || REC_EMP.ENAME);
END;
/
    