DECLARE
    CURSOR CUR_EMP IS
        SELECT ENAME, JOB, SAL, COMM FROM EMP WHERE DEPTNO = 10;
    
BEGIN
    FOR R_CUR_EMP IN CUR_EMP
    LOOP
        INSERT INTO BONUS(ENAME, JOB, SAL, COMM) VALUES(R_CUR_EMP.ENAME, R_CUR_EMP.JOB, R_CUR_EMP.SAL, R_CUR_EMP.COMM);
        -- 
    END LOOP;
    -- END LOOP 하는 순간 CURSOR 종료
    
    --DBMS_OUTPUT.PUT_LINE('TOTAL'||TO_CHAR(CUR_EMP%ROWCOUNT)||'ROWS PROCESSED');
    --  CURSOR + FOR LOOP 를 사용하면 OPEN, FETCH, CLOSE를 암시적으로 처리하기 때문에 ROWCOUNT을 알수 없음
    
    COMMIT;
    
    -- LOOP 내 OPEN, FETCH, CLOSE를 명시하지 않아도 처리됨
END;
/
