SELECT * from tab ORDER BY TABTYPE;
SELECT COUNT(*) FROM ORDERS;

CREATE TABLE CUSTOMER_T AS 
    (SELECT * FROM (SELECT * FROM CUSTOMER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000);
    
CREATE TABLE PRODUCT_T AS 
    (SELECT * FROM PRODUCT WHERE ROWNUM<=1000);
    
CREATE TABLE ORDERS_T AS 
    (SELECT * FROM (SELECT * FROM ORDERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000);

CREATE TABLE ZIPCODE_T AS 
    (SELECT * FROM (SELECT * FROM ZIPCODE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000); 

CREATE TABLE ORDER_ITEMS_T AS 
    (SELECT * FROM (SELECT * FROM ORDER_ITEMS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000); 
    
SELECT * FROM CUSTOMER;    

SELECT COUNT(*) FROM CUSTOMER_T;    
SELECT COUNT(*) FROM PRODUCT_T;
SELECT COUNT(*) FROM ORDERS_T GROUP BY ID;
SELECT COUNT(*) FROM ORDERS_T;
SELECT COUNT(*) FROM ZIPCODE_T;
SELECT COUNT(*) FROM ORDER_ITEMS_T;

SELECT SUBSTR(C.ADDRESS1, 1,2), SUM(O.ORDER_TOTAL) FROM ORDERS_T O, CUSTOMER_T C
WHERE C.ID = O.CUSTOMER_ID
GROUP BY SUBSTR(C.ADDRESS1, 1,2);

SELECT * FROM DEPT;
SELECT * FROM EMP;
SELECT * FROM CUSTOMER_T;
SELECT * FROM ORDERS_T;

SELECT * FROM ORDER_ITEMS_T;

SELECT T.ID, D.DNAME, E.MGR, E.DEPTNO, T.ADDRESS1 FROM DEPT D, EMP E, CUSTOMER_T T
WHERE D.DEPTNO = E.DEPTNO AND E.MGR = T.ACCOUNT_MGR;

SELECT T.ID, D.DNAME, E.MGR, E.DEPTNO, T.ADDRESS1 FROM EMP E, DEPT D, CUSTOMER_T T
WHERE D.DEPTNO(+) = E.DEPTNO AND E.MGR = T.ACCOUNT_MGR(+)
GROUP BY T.ID, D.DNAME, E.MGR, E.DEPTNO, T.ADDRESS1
ORDER BY T.ID;

SELECT T.ID, D.DNAME, E.MGR, E.DEPTNO, T.ADDRESS1, SUM(O.ORDER_TOTAL) AS SUM_ORDER FROM EMP E, DEPT D, CUSTOMER_T T, ORDERS_T O
WHERE D.DEPTNO(+) = E.DEPTNO AND E.MGR = T.ACCOUNT_MGR(+) AND T.ID = O.CUSTOMER_ID
GROUP BY T.ID, D.DNAME, E.MGR, E.DEPTNO, T.ADDRESS1
ORDER BY T.ID;




SELECT * FROM ORDERS_T;
SELECT * FROM ORDER_ITEMS;
SELECT * FROM ZIPCODE; 
SELECT * FROM CUSTOMER;
SELECT * FROm ORDERS;

SELECT * FROM ORDER_ITEMS;

SELECT * FROM CUSTOMER WHERE SUBSTR(ADDRESS1, 1, 2) = '서울';


SELECT * FROM CUSTOMER;

SELECT C.NAME, O.CUSTOMER_ID, COUNT(O.ORDER_TOTAL) AS COUNT_OF_TOTAL, SUM(O.ORDER_TOTAL) AS SUM_OF_TOTAL FROM CUSTOMER C, ORDERS O
WHERE O.CUSTOMER_ID = C.ID AND SUBSTR(ADDRESS1, 1,2) = '서울' AND O.ORDER_TOTAL>0
GROUP BY C.NAME, O.CUSTOMER_ID
ORDER BY COUNT_OF_TOTAL DESC;
