SELECT M.MEMBER_NO, M.MEMBER_NAME, A.ACC_NO, C.CARD_NAME
FROM MEMBER M, MEMBER_ACCOUNT A , MEMBER_CARD C WHERE M.MEMBER_NO = A.MEMBER_NO AND A.ACC_NO = C.ACC_NO AND CARD_NAME='하나카드1';

-- 하나카드1을 사용하는 고객을 찾는 쿼리
-- 관리자의 입장에서 어떤 카드가 가장 많이 사용하는지 알아볼때 사용

SELECT A.MEMBER_NAME, A.CARD_NO ,B.TOTAL_AMOUNT FROM (SELECT M.MEMBER_NO, M.MEMBER_NAME, A.ACC_NO, C.CARD_NO
FROM MEMBER M, MEMBER_ACCOUNT A , MEMBER_CARD C WHERE M.MEMBER_NO = A.MEMBER_NO AND A.ACC_NO = C.ACC_NO) A,
(SELECT CARD_NO, SUM(AMOUNT) AS TOTAL_AMOUNT FROM TRANSACTION_HISTORY GROUP BY CARD_NO) B
WHERE A.CARD_NO = B.CARD_NO;

-- 거래가 발생한 카드 중에서, 사람별로 가장 많은 거래가 발생한 카드 (주거래 카드)를 알아보는 쿼리