DROP TABLE CUSTOMER_T;
SELECT * FROM CUSTOMER ORDER BY ID;
CREATE TABLE CUSTOMER_T AS 
    (SELECT * FROM (SELECT * FROM CUSTOMER ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 1000000);
SELECT * FROM CUSTOMER ORDER BY ID;

CREATE TABLE PRODUCT_T AS 
    (SELECT * FROM PRODUCT WHERE ROWNUM<=1000);
    
CREATE TABLE ORDERS_T AS 
    (SELECT * FROM (SELECT * FROM ORDERS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000);

CREATE TABLE ZIPCODE_T AS 
    (SELECT * FROM (SELECT * FROM ZIPCODE ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000); 

CREATE TABLE ORDER_ITEMS_T AS 
    (SELECT * FROM (SELECT * FROM ORDER_ITEMS ORDER BY DBMS_RANDOM.VALUE) WHERE ROWNUM <= 100000);
    
----------------

SELECT O.ID, COUNT(O.ID) AS CNT FROM ORDER_ITEMS OI, ORDERS O
WHERE OI.ORDER_ID = O.ID
AND O.STATUS in (2,3,4)
GROUP BY O.ID
ORDER BY CNT DESC;

SELECT * FROM EMP;
SELECT * FROM CUSTOMER;
SELECT * FROM ORDERS;

SELECT C.ID, C.NAME O.SUM_TOTAL FROM CUSTOMER C, (
SELECT CUSTOMER_ID, SUM(ORDER_TOTAL) AS SUM_TOTAL FROM ORDERS O GROUP BY CUSTOMER_ID ORDER BY SUM_TOTAL DESC) O
WHERE C.ID = O.CUSTOMER_ID;

