/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-15 09:04:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/D:/DynamicHana/DynamicHana/src/main/webapp/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1631693945341L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<title>테스트</title>\n");
      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"./common.css\">\n");
      out.write("\n");
      out.write("<script src=\"./jquery-3.4.1.min.js\"></script>\n");
      out.write("<script src=\"http://code.highcharts.com/highcharts.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<style>\n");
      out.write("html, body {\n");
      out.write("	width: 100%;\n");
      out.write("	height: 100%;\n");
      out.write("	margin: 0;\n");
      out.write("	padding: 0;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table_center {\n");
      out.write("	margin-left: auto;\n");
      out.write("	margin-right: auto;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".table_td_image {\n");
      out.write("	width: 100%;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("	<table class=\"table_center\" style=\"width: 1000px;\">\n");
      out.write("		<tr>\n");
      out.write("			<td style=\"height: 80px;\">&nbsp;</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td><span style=\"font-size: 20px;\"><b>김미미님의 2021년 7월\n");
      out.write("						레포트</b></span></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td style=\"height: 10px;\"></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td>\n");
      out.write("				<table style=\"width: 900px;\">\n");
      out.write("					<tr style=\"height: 40px;\">\n");
      out.write("						<td></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>총 거래금액</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>총 거래 건수</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>사용카드</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>보유포인트</b></span></td>\n");
      out.write("					</tr>\n");
      out.write("					<tr style=\"height: 40px;\">\n");
      out.write("						<td></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>321,000원</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>45건</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>하나 AAA카드</b></span></td>\n");
      out.write("						<td><span style=\"font-size: 16px;\"><b>46,400점</b></span></td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td style=\"height: 10px;\"><hr></td>\n");
      out.write("		</tr>\n");
      out.write("		<tr>\n");
      out.write("			<td style=\"height: 300px;\">\n");
      out.write("\n");
      out.write("				<table class=\"table_center\" style=\"width: 900px;\">\n");
      out.write("					<tr>\n");
      out.write("						<td>\n");
      out.write("							<div id=\"container1\"\n");
      out.write("								style=\"width: 450px; height: 300px; margin: 0 auto\"></div>\n");
      out.write("						</td>\n");
      out.write("						<td rowspan='2' style=\"width: 450px; vertical-align: top;\">\n");
      out.write("							상세 거래 항목\n");
      out.write("							<table class=\"table_center\" style=\"width: 450px;\">\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #ffffff; background-color: rgb(68, 114, 196);\">NO</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #ffffff; background-color: rgb(68, 114, 196);\">거래일시</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #ffffff; background-color: rgb(68, 114, 196);\">카테고리</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #ffffff; background-color: rgb(68, 114, 196);\">항목명</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #ffffff; background-color: rgb(68, 114, 196);\">금액</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">1</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">2021-08-14<br>19:32:14\n");
      out.write("									</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">음식</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">신전떡</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">32,000원</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">2</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">2021-08-14<br>19:32:14\n");
      out.write("									</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">음식</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">신전떡</td>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">32,000원</td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">3</td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">4</td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(207, 213, 234);\">5</td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(207, 213, 234);\"></td>\n");
      out.write("								</tr>\n");
      out.write("								<tr>\n");
      out.write("									<td\n");
      out.write("										style=\"text-align: center; color: #000000; background-color: rgb(233, 235, 245);\">&nbsp;</td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("									<td\n");
      out.write("										style=\"color: #000000; background-color: rgb(233, 235, 245);\"></td>\n");
      out.write("								</tr>\n");
      out.write("							</table>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("					<tr>\n");
      out.write("						<td>\n");
      out.write("							<div id=\"container2\"\n");
      out.write("								style=\"width: 450px; height: 300px; margin: 0 auto\"></div>\n");
      out.write("						</td>\n");
      out.write("					</tr>\n");
      out.write("				</table>\n");
      out.write("			</td>\n");
      out.write("		</tr>\n");
      out.write("	</table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("	<script language=\"JavaScript\">\n");
      out.write("		$(document).ready(\n");
      out.write("				function() {\n");
      out.write("\n");
      out.write("					var chart = {\n");
      out.write("						type : 'column'\n");
      out.write("					};\n");
      out.write("					var title = {\n");
      out.write("						text : '주간 거래 분석',\n");
      out.write("						align : 'left'\n");
      out.write("					};\n");
      out.write("					var subtitle = {\n");
      out.write("						text : ''\n");
      out.write("					};\n");
      out.write("					var xAxis = {\n");
      out.write("						type : 'category',\n");
      out.write("						labels : {\n");
      out.write("							rotation : -45,\n");
      out.write("							style : {\n");
      out.write("								fontSize : '13px',\n");
      out.write("								fontFamily : 'Verdana, sans-serif'\n");
      out.write("							}\n");
      out.write("						}\n");
      out.write("					};\n");
      out.write("					var yAxis = {\n");
      out.write("						min : 0,\n");
      out.write("						title : {\n");
      out.write("							text : ''\n");
      out.write("						}\n");
      out.write("					};\n");
      out.write("					var tooltip = {\n");
      out.write("						pointFormat : '{point.y:.1f}'\n");
      out.write("					};\n");
      out.write("					var credits = {\n");
      out.write("						enabled : false\n");
      out.write("					};\n");
      out.write("					var legend = {\n");
      out.write("						enabled : false,\n");
      out.write("						layout : 'vertical',\n");
      out.write("						align : 'right',\n");
      out.write("						verticalAlign : 'top',\n");
      out.write("						borderWidth : 0\n");
      out.write("					};\n");
      out.write("					var series = [ {\n");
      out.write("						name : 'Project',\n");
      out.write("						data : [ [ '7월 1주', 170000 ], [ '7월 2주', 150000 ],\n");
      out.write("								[ '7월 3주', 80000 ], [ '7월 4주', 160000 ],\n");
      out.write("								[ '7월 5주', 250000 ] ],\n");
      out.write("						dataLabels : {\n");
      out.write("							enabled : true,\n");
      out.write("							// rotation: -90,\n");
      out.write("							// color: '#FFFFFF',\n");
      out.write("							// align: 'right',\n");
      out.write("							format : '{point.y:.1f}', // one decimal\n");
      out.write("							// y: 10, // 10 pixels down from the top\n");
      out.write("							style : {\n");
      out.write("								// fontSize: '13px',\n");
      out.write("								fontFamily : 'Verdana, sans-serif'\n");
      out.write("							}\n");
      out.write("						}\n");
      out.write("					} ];\n");
      out.write("\n");
      out.write("					var json = {};\n");
      out.write("					json.chart = chart;\n");
      out.write("					json.title = title;\n");
      out.write("					json.subtitle = subtitle;\n");
      out.write("					json.xAxis = xAxis;\n");
      out.write("					json.yAxis = yAxis;\n");
      out.write("					json.tooltip = tooltip;\n");
      out.write("					json.legend = legend;\n");
      out.write("					json.credits = credits;\n");
      out.write("					json.series = series;\n");
      out.write("\n");
      out.write("					$('#container1').highcharts(json);\n");
      out.write("\n");
      out.write("					var chart = {\n");
      out.write("						type : 'column'\n");
      out.write("					};\n");
      out.write("					var title = {\n");
      out.write("						text : '요일별 거래 분석',\n");
      out.write("						align : 'left'\n");
      out.write("					};\n");
      out.write("					var subtitle = {\n");
      out.write("						text : ''\n");
      out.write("					};\n");
      out.write("					var xAxis = {\n");
      out.write("						type : 'category',\n");
      out.write("						labels : {\n");
      out.write("							rotation : -45,\n");
      out.write("							style : {\n");
      out.write("								fontSize : '13px',\n");
      out.write("								fontFamily : 'Verdana, sans-serif'\n");
      out.write("							}\n");
      out.write("						}\n");
      out.write("					};\n");
      out.write("					var yAxis = {\n");
      out.write("						min : 0,\n");
      out.write("						title : {\n");
      out.write("							text : ''\n");
      out.write("						}\n");
      out.write("					};\n");
      out.write("					var tooltip = {\n");
      out.write("						pointFormat : '{point.y:.1f}'\n");
      out.write("					};\n");
      out.write("					var credits = {\n");
      out.write("						enabled : false\n");
      out.write("					};\n");
      out.write("					var legend = {\n");
      out.write("						enabled : false,\n");
      out.write("						layout : 'vertical',\n");
      out.write("						align : 'right',\n");
      out.write("						verticalAlign : 'top',\n");
      out.write("						borderWidth : 0\n");
      out.write("					};\n");
      out.write("					var series = [ {\n");
      out.write("						name : 'Project',\n");
      out.write("						data : [ [ '일요일', 170000 ], [ '월요일', 150000 ],\n");
      out.write("								[ '화요일', 80000 ], [ '수요일', 160000 ],\n");
      out.write("								[ '목요일', 250000 ], [ '금요일', 190000 ],\n");
      out.write("								[ '토요일', 360000 ] ],\n");
      out.write("						dataLabels : {\n");
      out.write("							enabled : true,\n");
      out.write("							// rotation: -90,\n");
      out.write("							// color: '#FFFFFF',\n");
      out.write("							// align: 'right',\n");
      out.write("							format : '{point.y:.1f}', // one decimal\n");
      out.write("							// y: 10, // 10 pixels down from the top\n");
      out.write("							style : {\n");
      out.write("								// fontSize: '13px',\n");
      out.write("								fontFamily : 'Verdana, sans-serif'\n");
      out.write("							}\n");
      out.write("						}\n");
      out.write("					} ];\n");
      out.write("\n");
      out.write("					var json = {};\n");
      out.write("					json.chart = chart;\n");
      out.write("					json.title = title;\n");
      out.write("					json.subtitle = subtitle;\n");
      out.write("					json.xAxis = xAxis;\n");
      out.write("					json.yAxis = yAxis;\n");
      out.write("					json.tooltip = tooltip;\n");
      out.write("					json.legend = legend;\n");
      out.write("					json.credits = credits;\n");
      out.write("					json.series = series;\n");
      out.write("\n");
      out.write("					$('#container2').highcharts(json);\n");
      out.write("\n");
      out.write("				});\n");
      out.write("	</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
