-- T_CONS5.SQL
START T_CONS5.SQL

INSERT INTO EMPLOYEE VALUES('XMAN', '10'); -- 부모키가 없음, 제약사항 위배
INSERT INTO 부서(부서ID, 부서명) VALUES('10', '관리실');
INSERT INTO 부서(부서ID, 부서명) VALUES('20', '전산실');

INSERT INTO EMPLOYEE VALUES('XMAN', '10');
INSERT INTO EMPLOYEE VALUES('XMAN', 'XX'); -- 부모키가 없음, 제약사항 위배
DELETE FROM 부서 WHERE 부서ID = '10'; -- 자식 레코드 존재, 제약사항 위배

DROP TABLE 부서; -- 자식 레코드가 존재하기 때문에 삭제 불가
DROP TABLE 부서 CASCADE CONSTRAINTS; -- 자식 레코드가 존재하더라도 삭제
DROP TABLE EMPLOYEE;

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'EMPLOYEE'; -- FOREIGN KEY 제약사항이 제거되어 있음

-- T_CONS5_2.SQL
START T_CONS5_2.SQL

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE
FROM DBA_CONSTRAINTS WHERE TABLE_NAME IN ('DEPARTMENT', 'EMPLOYEE');

INSERT INTO EMPLOYEE(사번, 이름, DEPTNO) VALUES('XMAN', 'TUNER', '10'); -- 부모키가 없음, 제약사항 위배

INSERT INTO DEPARTMENT ( DEPTNO,DNAME ) VALUES ( '10','관리팀' );
INSERT INTO DEPARTMENT ( DEPTNO,DNAME ) VALUES ( '20','전산팀' );
INSERT INTO DEPARTMENT ( DEPTNO,DNAME ) VALUES ( '30','영업팀' );

INSERT INTO EMPLOYEE ( 사번,이름,DEPTNO ) VALUES ( 'XMAN','TUNER',10 );
INSERT INTO EMPLOYEE ( 사번,이름,DEPTNO ) VALUES ( 'YMAN','DBA',20 );
INSERT INTO EMPLOYEE ( 사번,이름,DEPTNO ) VALUES ( 'ZMAN','DEVELOPER',30 );

SELECT * FROM DEPARTMENT;

SELECT * FROM EMPLOYEE;

DELETE FROM DEPARTMENT WHERE DEPTNO = 30; -- 자식 레코드 존재, 제약사항 위배
DELETE FROM DEPARTMENT WHERE DEPTNO = 10; -- 자식 레코드 존재, 제약사항 위배
UPDATE EMPLOYEE SET DEPTNO=20 WHERE DEPTNO=10; -- DEPTNO가 10인 것에 대해 20으로 변경 -> 10에 대한 FK 제약이 없어짐
DELETE FROM DEPARTMENT WHERE DEPTNO = 10; -- FK가 존재하지 않기 때문에 삭제 가능

