DROP TABLE DEPARTMENT;

DROP TABLE EMPLOYEE;

CREATE TABLE DEPARTMENT (
    DEPTNO   VARCHAR(2)
        CONSTRAINT DEPARTMENT_DEPTNO_PK PRIMARY KEY,
    DNAME    VARCHAR2(10)
        CONSTRAINT DEPARTMENT_DNAME_NN NOT NULL
);

CREATE TABLE EMPLOYEE (
    사번       VARCHAR2(8) PRIMARY KEY,
    이름       VARCHAR2(10),
    DEPTNO   VARCHAR2(2) NOT NULL,
    CONSTRAINT EMPLOYEE_DEPARTMENT_DEPTNO_FK FOREIGN KEY ( DEPTNO )
        REFERENCES DEPARTMENT ( DEPTNO )
);