DROP TABLE 何辑;

CREATE TABLE 何辑 (
    何辑ID   VARCHAR2(2)
        CONSTRAINT DEPARTMENT_何辑ID_PK PRIMARY KEY,
    何辑疙    VARCHAR2(10)
);

DROP TABLE EMPLOYEE;

CREATE TABLE EMPLOYEE (
    EMPID   VARCHAR2(8),
    何辑ID    VARCHAR2(2),
    CONSTRAINT EMPLOYEE_何辑_何辑ID_FK FOREIGN KEY ( 何辑ID )
        REFERENCES 何辑 ( 何辑ID )
);

DESC 何辑;
DESC EMPLOYEE;