-- TEMP 테이블 생성
DROP TABLE TEMP;
CREATE TABLE TEMP AS (SELECT NAME, BIRTH_DT FROM CUSTOMER);
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='CUSTOMER';

CREATE INDEX BIRTH_DT_IDX ON TEMP(BIRTH_DT);

SELECT * FROM ALL_IND_COLUMNS WHERE TABLE_NAME='TEMP';
SELECT * FROM USER_INDEXES WHERE TABLE_NAME='TEMP';

SELECT * FROM TEMP;

-- 인덱스가 없을 경우
SELECT * FROM CUSTOMER WHERE BIRTH_DT = TO_DATE('1961-07-29 22:58:04', 'YYYY-MM-DD HH24:MI:SS');

SELECT * FROM CUSTOMER WHERE BIRTH_DT = TO_DATE('1961-07-29', 'YYYY-MM-DD');

SELECT * FROM CUSTOMER WHERE TO_DATE(BIRTH_DT, 'YYYY-MM-DD HH24:MI:SS') = TO_DATE('1961-07-29 22:58:04', 'YYYY-MM-DD HH24:MI:SS');
--- 인덱스가 없기 때문에 위 아래 식 모두 COST에서 큰 차이를 보이지 않음


-- 인덱스가 있을 경우
SELECT * FROM TEMP WHERE BIRTH_DT = TO_DATE('1961-07-29 22:58:04', 'YYYY-MM-DD HH24:MI:SS');

SELECT * FROM TEMP WHERE BIRTH_DT = TO_DATE('1961-07-29', 'YYYY-MM-DD');

SELECT * FROM TEMP WHERE TO_DATE(BIRTH_DT, 'YYYY-MM-DD HH24:MI:SS') = TO_DATE('1961-07-29 22:58:04', 'YYYY-MM-DD HH24:MI:SS');

--- 좌변 가공했을 때 인덱스를 사용하지 못하기 때문에 COST가 상당히 발생
--- 좌변 가공을 하지 않으면 INDEX를 기준으로 TABLE ACCESS를 INDEX ROWID BATCHED 방식으로 하기 때문에 COST 절약


SELECT
    *
FROM
    TEMP
WHERE
    BIRTH_DT BETWEEN TO_DATE('1981-01-01','YYYY-MM-DD') AND TO_DATE('1981-09-30','YYYY-MM-DD');
    
SELECT
    *
FROM
    TEMP
WHERE
    BIRTH_DT BETWEEN TO_DATE('1981-01-01','YYYY-MM-DD') AND TO_DATE('1981-02-02','YYYY-MM-DD');
    
SELECT
    *
FROM
    TEMP
WHERE
    BIRTH_DT BETWEEN TO_DATE('1981-01-01 00:00:00','YYYY-MM-DD HH24:MI:SS') AND TO_DATE('1981-01-31 23:59:59','YYYY-MM-DD HH24:MI:SS');