-- View Merge
DROP VIEW V_DEPTEMP;

CREATE VIEW V_DEPTEMP AS SELECT E.EMPNO, E.ENAME, E.SAL, D.DNAME
FROM EMP E, DEPT D WHERE E.DEPTNO = D.DEPTNO;

SELECT * FROM V_DEPTEMP WHERE DNAME = 'SALES';

SELECT E.EMPNO, E.ENAME, E.SAL, D.DEPTNO, D.DNAME FROM EMP E, DEPT D
WHERE E.DEPTNO=D.DEPTNO AND D.DNAME='SALES';


-- Object Dependency
DROP TABLE BASE_TBL;
DROP VIEW DEPEN;

CREATE TABLE BASE_TBL(EMPNO_NEW, ENAME_NEW)
AS SELECT EMPNO, ENAME FROM EMP;

CREATE VIEW DEPEN AS SELECT EMPNO_NEW, ENAME_NEW FROM BASE_TBL;

SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'DEPEN'; -- VALID
DROP TABLE BASE_TBL;

SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'DEPEN'; -- INVALID

CREATE TABLE BASE_TBL(EMPNO_NEW, ENAME_NEW, DEPTNO_NEW) AS SELECT EMPNO, ENAME, DEPTNO FROM EMP;
SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'DEPEN'; -- INVALID
SELECT * FROM DEPEN;
SELECT OBJECT_NAME, STATUS FROM USER_OBJECTS WHERE OBJECT_NAME = 'DEPEN'; -- VALID

-- VIEW의 용도
--- 보안성
CREATE VIEW RESTRICT_SELECT(EMPNO_NEW, ENAME_NEW, DEPTNO_NEW) AS 
SELECT EMPNO, ENAME, DEPTNO FROM EMP WHERE SAL > 1500;

SELECT * FROM RESTRICT_SELECT; -- 보여주는 데이터 제한
--- 편리성
CREATE VIEW SIMPLE_VIEW AS SELECT EMP.EMPNO, EMP.ENAME, DEPT.DNAME, SALGRADE.GRADE
AS GD FROM EMP, DEPT, SALGRADE WHERE EMP.DEPTNO = DEPT.DEPTNO AND EMP.SAL BETWEEN SALGRADE.LOSAL AND SALGRADE.HISAL;
DESC SIMPLE_VIEW
SELECT * FROM SIMPLE_VIEW;
--- 독립성
CREATE TABLE BASE_TBL(EMPNO_NEW, ENAME_NEW) AS SELECT EMPNO, ENAME FROM EMP;
CREATE VIEW IND_VIEW AS SELECT * FROM BASE_TBL;
SELECT * FROM IND_VIEW;
ALTER TABLE BASE_TBL ADD(NEW_COL DATE); -- BASE TABLE변경
SELECT * FROM IND_VIEW;   --  INDEPENDENCE    OF    TABLE CHANGE
--- DIFFERENT APPEARANCES FOR THE SAME DATA

CREATE TABLE DIFF_RETURN_TBL AS
SELECT OWNER, TABLE_NAME FROM DBA_TABLES;

SELECT * FROM DIFF_RETURN_TBL;  

CREATE OR REPLACE VIEW DIFF_RETURN_VIEW AS SELECT * FROM DIFF_RETURN_TBL WHERE OWNER = USER; -- 테이블이 존재하다면 대체
SELECT * FROM DIFF_RETURN_TBL;

GRANT SELECT ON DIFF_RETURN_VIEW TO PUBLIC;

SELECT * FROM DIFF_RETURN_TBL;