SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL, D.Dname FROM EMP E, DEPT D
WHERE D.DEPTNO = E.DEPTNO AND JOB='MANAGER' AND SAL>2500;

SELECT * FROM SALGRADE;
SELECT E.EMPNO, E.ENAME, E.SAL, S.GRADE FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL AND S.GRADE = 4;

SELECT E.EMPNO, E.DEPTNO, D.DNAME, E.SAL, S.GRADE FROM EMP E, DEPT D, SALGRADE S
WHERE E.DEPTNO = D.DEPTNO AND E.SAL BETWEEN S.LOSAL AND S.HISAL;

SELECT E.ENAME, E2.ENAME FROM EMP E, EMP E2 WHERE E.EMPNO = E2.MGR;

SELECT E.ENAME, E2.ENAME, E3.ENAME FROM EMP E, EMP E2, EMP E3
WHERE E.MGR = E2.EMPNO AND E2.MGR = E3.EMPNO;

SELECT D.DNAME, E.ENAME, D.DEPTNO FROM DEPT D, EMP E
WHERE D.DEPTNO = E.DEPTNO;

SELECT E.EMPNO, E.ENAME, E.DEPTNO, E.SAL, IV.MAX_SAL FROM EMP E, (SELECT DEPTNO, MAX(SAL) AS MAX_SAL FROM EMP GROUP BY DEPTNO) IV
WHERE E.DEPTNO = IV.DEPTNO AND E.SAL = IV.MAX_SAL;

SELECT ENAME, DEPTNO, SAL FROM EMP WHERE SAL<(SELECT AVG(E.SAL) FROM EMP E, SALGRADE S
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL
AND S.GRADE=2);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'CUSTOMER';

SELECT DEPTNO, ENAME, JOB, SAL, (SELECT ROUND(AVG(SAL),0) FROM EMP E2 WHERE E2.DEPTNO = E.DEPTNO) AS AVG_SAL FROM EMP E ;


SELECT EMPNO, ENAME, DEPTNO, SAL FROM EMP WHERE (DEPTNO, SAL) IN (SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO);

SELECT DEPTNO, MAX(SAL) FROM EMP GROUP BY DEPTNO;