DESC TBL_BOARD;
DROP TABLE T_BOARD;

CREATE TABLE T_BOARD(
    NO NUMBER(5) PRIMARY KEY,
    TITLE       VARCHAR2(300) NOT NULL,
    WRITER      VARCHAR2(100) NOT NULL,
    CONTENT     VARCHAR2(2000) NOT NULL,
    VIEW_CNT    NUMBER(5) DEFAULT 0,
    REG_DATE    DATE DEFAULT SYSDATE
);

DROP SEQUENCE SEQ_T_BOARD_NO;
CREATE SEQUENCE SEQ_T_BOARD_NO;

INSERT INTO T_BOARD(NO, TITLE, WRITER, CONTENT) VALUES(SEQ_T_BOARD_NO.NEXTVAL, '제목입니다', '홍길동', '내용입니다');
INSERT INTO T_BOARD(NO, TITLE, WRITER, CONTENT) VALUES(SEQ_T_BOARD_NO.NEXTVAL, '제목입니다2', '홍길동2', '내용입니다2');
COMMIT;

SELECT * FROM T_BOARD;

DROP TABLE T_MEMBER;
CREATE TABLE T_MEMBER(
    ID VARCHAR2(20) PRIMARY KEY,
    NAME VARCHAR2(20) NOT NULL,
    PASSWORD VARCHAR2(20) NOT NULL,
    EMAIL_ID VARCHAR2(30),
    EMAIL_DOMAIN VARCHAR(20),
    TEL1 CHAR(3),
    TEL2 CHAR(4),
    TEL3 CHAR(4),
    POST CHAR(7),
    BASIC_ADDR VARCHAR2(200),
    DETAIL_ADDR VARCHAR2(200),
    TYPE CHAR(1) DEFAULT 'U',
    REG_DATE DATE DEFAULT SYSDATE
);


INSERT INTO T_MEMBER(ID, NAME, PASSWORD, EMAIL_ID, EMAIL_DOMAIN, TEL1, TEL2, TEL3, POST, BASIC_ADDR, DETAIL_ADDR)
VALUES('9bonseong','구본성','1234','9bonseong','naver.com','010','4773','9853','12345','서울특별시','동대문구 이문로 199 503');
commit;

INSERT INTO T_MEMBER(ID, NAME, PASSWORD, EMAIL_ID, EMAIL_DOMAIN, TEL1, TEL2, TEL3, POST, BASIC_ADDR, DETAIL_ADDR)
VALUES('abc123','김충만','1234','abc123','naver.com','010','4773','9853','12345','서울특별시','동대문구 이문로 199 503');

INSERT INTO T_MEMBER(ID, NAME, PASSWORD, EMAIL_ID, EMAIL_DOMAIN, TEL1, TEL2, TEL3, POST, BASIC_ADDR, DETAIL_ADDR)
VALUES('qwe123','안재훈','1234','qwe123','naver.com','010','4773','9853','12345','서울특별시','동대문구 이문로 199 503');

INSERT INTO T_MEMBER(ID, NAME, PASSWORD, EMAIL_ID, EMAIL_DOMAIN, TEL1, TEL2, TEL3, POST, BASIC_ADDR, DETAIL_ADDR, TYPE)
VALUES('ADMIN','관리자','ADMIN','ADMIN','naver.com','010','4773','9853','12345','서울특별시','동대문구 이문로 199 503', 'S');

select * from t_board order by no;
commit;



INSERT INTO T_BOARD(NO, TITLE, WRITER, CONTENT) VALUES (1234,'1234','1234','1234');

CREATE TABLE T_BOARD_FILE(
    NO  NUMBER(5)   PRIMARY KEY,
    BOARD_NO    NUMBER(5)   NOT NULL,
    FILE_ORI_NAME   VARCHAR2(300),
    FILE_SAVE_NAME  VARCHAR2(300),
    FILE_SIZE   NUMBER(10),
    CONSTRAINT T_BOARD_FILE_NO_FK FOREIGN KEY(BOARD_NO) REFERENCES T_BOARD(NO)
);

CREATE SEQUENCE SEQ_T_BOARD_FILE_NO NOCACHE;

select * from t_board_file;

DROP TABLE T_BOARD_FILE;

SELECT SEQ_T_BOARD_NO.CURRVAL FROM DUAL;

SELECT 