DROP TABLE SCOTT.CUST3;
CREATE TABLE SCOTT.CUST3(
    ID      VARCHAR2(8)     NOT NULL CONSTRAINT CUST3_ID_UK UNIQUE,
    PWD     VARCHAR2(8)     NOT NULL,
    NAME    VARCHAR2(20),
    SEX     CHAR(1)         DEFAULT 'M' CONSTRAINT CUST3_SEX_CK CHECK (SEX IN ('F', 'M')),
    MOBILE  VARCHAR2(14)    UNIQUE, -- UNIQUE는 NULL을 허용
    AGE     NUMBER(3)       DEFAULT 18
)