DROP SEQUENCE ORDER_SEQ;
CREATE SEQUENCE SCOTT.ORDER_SEQ
    INCREMENT BY    1 -- 1씩 증가
    START WITH      1 -- 시작값
    MAXVALUE        9999999 -- 최댓값
    MINVALUE        1 
    NOCYCLE         -- CYCLE : 최댓값까지 가면 다시 1부터
    CACHE           3000; -- 자주 사용하는 값
    
SELECT ORDER_SEQ.CURRVAL FROM DUAL; -- 에러, 아직 시퀀스의 값이 존재하지 않음

SELECT ORDER_SEQ.NEXTVAL FROM DUAL; -- 1
SELECT ORDER_SEQ.CURRVAL FROM DUAL; -- 1
ROLLBACK; -- 시퀀스는 롤백되지 않음

SELECT ORDER_SEQ.NEXTVAL FROM DUAL;


-- ORDER_TBL.SQL
START ORDER_TBL.SQL

INSERT INTO ORDERS(ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL, 'direct', 166, 1, 7499);

INSERT INTO SCOTT.ORDERS(ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(SCOTT.ORDER_SEQ.NEXTVAL, SYSDATE, 'online', 200, 3, 7521);

SELECT * FROM ORDERS;

COMMIT;

INSERT INTO ORDERS(ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL,SYSDATE, 'online', 135, 2, 7844);

ROLLBACK;

SELECT ORDER_ID FROM ORDERS;
SELECT ORDER_SEQ.CURRVAL FROM DUAL; -- 시퀀스는 롤백되지 않음!

INSERT INTO ORDERS(ORDER_ID, ORDER_DATE, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES(ORDER_SEQ.NEXTVAL, SYSDATE, 'direct', 135, 4, 7844);

SELECT * FROM ORDERS; -- HOLE 발생

-- MAX+1 방식 -> 속도, 연산문제
INSERT INTO scott.ORDERS(ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
VALUES((SELECT MAX(ORDER_ID)+1 FROM scott.ORDERS),'direct',335,1,7654);

SELECT * FROM ORDERS;


-- ORDER_ID.SQL
START ORDER_ID_TBL.SQL;
/*
DECLARE -- 선언부
	V_ORDER_SEQ NUMBER(12);
BEGIN -- 실행부
	SELECT ORDER_SEQ INTO V_ORDER_SEQ
	FROM ORDER_ID
	FOR UPDATE; -- 수정을 위한 LOCK

	INSERT INTO ORDERS(ORDER_ID, ORDER_MODE, CUSTOMER_ID, ORDER_STATUS, SALES_ID)
	VALUES(V_ORDER_SEQ, 'direct', 3320, 2, 7677); -- 무결성 제약조건 위배, 부모키가 없음

	UPDATE ORDER_ID SET ORDER_SEQ = ORDER_SEQ +1;
	COMMIT;
END;
*/

select * from orders;


-- assignment
SELECT ORDER_SEQ.CURRVAL FROM DUAL;
SELECT ORDER_SEQ.NEXTVAL FROM DUAL;

ALTER SEQUENCE ORDER_SEQ INCREMENT BY -101;
SELECT ORDER_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE ORDER_SEQ INCREMENT BY 9;
SELECT ORDER_SEQ.NEXTVAL FROM DUAL;
ALTER SEQUENCE ORDER_SEQ INCREMENT BY 1;


SELECT LAST_NUMBER FROM USER_SEQUENCES WHERE SEQUENCE_NAME = 'ORDER_SEQ';

SELECT LPAD(TO_CHAR(ORDER_SEQ.NEXTVAL), 8, '0') AS NO FROM DUAL;

SELECT TO_CHAR(ORDER_SEQ.NEXTVAL, 'fm00000000') FROM DUAL;



