DROP TABLE SCOTT.UNIV;
CREATE TABLE SCOTT.UNIV(
    COLLEGE VARCHAR2(20) NOT NULL,
    DEPT VARCHAR2(20) NOT NULL,
    
    CONSTRAINT UNIV_CONS PRIMARY KEY(COLLEGE, DEPT)
);

SELECT * FROM UNIV;

INSERT INTO UNIV(COLLEGE, DEPT) VALUES('Natural Sciences', 'Mathmatics');
INSERT INTO UNIV(COLLEGE, DEPT) VALUES('Natural Sciences', 'Statistics');

---------------------

DROP TABLE EMP_SAL;
CREATE TABLE EMP_SAL(
EMPNO NUMBER(3),
PAID_DATE DATE,
PAID_SAL NUMBER(4),
CONSTRAINT EMP_SAL_PK PRIMARY KEY(EMPNO,PAID_DATE)
);

INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(100, TO_DATE('2021-03-17', 'yyyy-mm-dd'), 1000);
INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(101, TO_DATE('2021-03-17', 'yyyy-mm-dd'), 2000);
INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(100, TO_DATE('2021-04-17', 'yyyy-mm-dd'), 1000);
INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(101, TO_DATE('2021-04-17', 'yyyy-mm-dd'), 2000);
INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(100, TO_DATE('2021-05-17', 'yyyy-mm-dd'), 1000);
INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(101, TO_DATE('2021-05-17', 'yyyy-mm-dd'), 2000);

INSERT INTO EMP_SAL (EMPNO, PAID_DATE, PAID_SAL) VALUES(101, TO_DATE('2021-05-17', 'yyyy-mm-dd'), 3000); -- ¿À·ù

SELECT * FROM EMP_SAL;