DROP TABLE SCOTT.CUST4;
CREATE TABLE SCOTT.CUST4(
    ID      VARCHAR2(8)     CONSTRAINT CUST4_ID_PK PRIMARY KEY, -- PK는 테이블당 1개만 가능
    PWD     VARCHAR2(8)     NOT NULL,
    NAME    VARCHAR2(20),
    SEX     CHAR(1)         DEFAULT 'M' CONSTRAINT CUST4_SEX_CK CHECK (SEX IN ('F', 'M')),
    MOBILE  VARCHAR2(14)    CONSTRAINT CUST4_MOBILE_UK UNIQUE, -- UNIQUE는 NULL을 허용
    AGE     NUMBER(3)       DEFAULT 18
)