BEGIN
    UPDATE MEMBER_ACCOUNT SET BALANCE = BALANCE - 1000 WHERE ACC_NO = '111-111-111'; 
    INSERT INTO TRANSACTION_HISTORY(HISTORY_TIME, AMOUNT, CATEGORY, STORE, CARD_NO) VALUES('11:00', 1000, '미용', '올리브영', '1010-1010-1010-1010'); 
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
END;    
/

-- 거래가 발생할때 사용한 카드와 연결된 계좌의 금액을 감소시킴과 동시에
-- 소비에 대한 가맹점, 금액, 사용한 카드번호, 일자 등을 로그 테이블에 기록할 수 있도록 함

BEGIN
    INSERT INTO MONTHLY_SUMMARY(MOST_EXPENDITURE_CATEGORIES, MAX_OF_EXPENDITURE, AVG_OF_EXPENDITURE_PER_CASE, MAX_EXPENDITURE_AREA, MAIN_CARD_NAME, CARD_NO)
    VALUES ((SELECT CATEGORY FROM (SELECT CATEGORY, COUNT(CATEGORY) AS CNT FROM TRANSACTION_HISTORY WHERE CARD_NO='1010-1010-1010-1010' GROUP BY CATEGORY ORDER BY CNT DESC) WHERE ROWNUM=1),
    (SELECT MAX(AMOUNT) AS MAX FROM TRANSACTION_HISTORY WHERE CARD_NO= '1010-1010-1010-1010'),
    (SELECT ROUND(SUM(AMOUNT)/COUNT(AMOUNT)) AS AVG FROM TRANSACTION_HISTORY WHERE CARD_NO= '1010-1010-1010-1010'),
    '서울 강남구', '주거래카드', '1010-1010-1010-1010');
    
    INSERT INTO SUMMARY_LOG(SENDING_DATE, TOTAL, OPEN_RATE) VALUES(SYSDATE, 100000, 30000);
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
END;    

-- 한달간 발생한 거래에 대해 매월 마지막 날 쯤, 배치 프로그램에 의해 해당월의 최다 지출 카테고리, 최다 지출액, 평균 지출액 등에 대해 계산하고, 인사이트에 대해 월간 요약 테이블에 인서트한다,
-- 또한 최종적으로 데이터가 모두 모이면 LOG테이블에 전체 보고서를 발송할 고객의 수, 예상 열람 고객의 수 등을 기입한다