SELECT * FROM EMP;
SELECT E.ENAME||' ''S MANAGER IS '||M.ENAME FROM EMP E, EMP M WHERE E.MGR = M.EMPNO ORDER BY M.ENAME; 

SELECT E.ENAME||' ''S MANAGER IS '||NVL(M.ENAME,'NOBODY') FROM EMP E, EMP M WHERE E.MGR = M.EMPNO(+) ORDER BY M.ENAME; 




SELECT * FROM(
SELECT DEPTNO, ENAME, JOB, SAL,
DENSE_RANK() OVER (PARTITION BY DEPTNO ORDER BY SAL DESC) AS RANK FROM EMP)
WHERE RANK<=3;

SELECT A.ENAME, COUNT(A.ENAME)+1 AS RANK
FROM EMP A, EMP B
WHERE A.DEPTNO = B.DEPTNO AND A.SAL < B.SAL
GROUP BY A.ENAME;

SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL, NVL(R.RANK,1) RANK
FROM EMP E, (
SELECT A.ENAME, COUNT(A.ENAME)+1 AS RANK
FROM EMP A, EMP B
WHERE A.DEPTNO = B.DEPTNO AND A.SAL < B.SAL
GROUP BY A.ENAME
) R
WHERE E.ENAME = R.ENAME(+)
ORDER BY E.DEPTNO, E.SAL DESC;


-----------------


CREATE TABLE SYSTEM(SYSTEM_ID   VARCHAR2(10),
                    SYSTEM_NAME VARCHAR2(20));

INSERT INTO SYSTEM VALUES('XXX','혜화DB');
INSERT INTO SYSTEM VALUES('YYY','강남DB');
INSERT INTO SYSTEM VALUES('ZZZ','영등포DB');

CREATE TABLE RESOURCE_USAGE(SYSTEM_ID   VARCHAR2(5),
                            RESOURCE_NAME   VARCHAR2(10));

INSERT INTO RESOURCE_USAGE VALUES('XXX','FTP');
INSERT INTO RESOURCE_USAGE VALUES('YYY','FTP');
INSERT INTO RESOURCE_USAGE VALUES('YYY','TELNET');
INSERT INTO RESOURCE_USAGE VALUES('YYY','EMAIL');                                       


SELECT * FROM SYSTEM;
SELECT * FROM RESOURCE_USAGE;


SELECT DISTINCT S.SYSTEM_ID AS SYSTEM , S.SYSTEM_NAME,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID=S.SYSTEM_ID AND RESOURCE_NAME = 'FTP'  ),1,'사용','미사용') AS FTP,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID=S.SYSTEM_ID AND RESOURCE_NAME = 'TELNET '  ),1,'사용','미사용') AS TELNET,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID=S.SYSTEM_ID AND RESOURCE_NAME = 'EMAIL'  ),1,'사용','미사용') AS EMAIL
FROM SYSTEM S, RESOURCE_USAGE R 
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+)
ORDER BY SYSTEM;

SELECT * FROM SYSTEM;
SELECT * FROM RESOURCE_USAGE;

SELECT DISTINCT S.SYSTEM_ID AS SYSTEM, S.SYSTEM_NAME,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID = S.SYSTEM_ID AND RESOURCE_NAME = 'FTP'),1,'사용','미사용') AS FTP,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID = S.SYSTEM_ID AND RESOURCE_NAME = 'TELNET'),1,'사용','미사용') AS TELNET,
DECODE((SELECT COUNT(*) FROM RESOURCE_USAGE WHERE SYSTEM_ID = S.SYSTEM_ID AND RESOURCE_NAME = 'EMAIL'),1,'사용','미사용') AS EMAIL
FROM SYSTEM S, RESOURCE_USAGE R
WHERE S.SYSTEM_ID = R.SYSTEM_ID(+)
ORDER BY SYSTEM;


SELECT A.DEPTNO, A.ENAME, A.SAL, ROUND(A.SAL/SUM(B.SAL),4)*100 AS SAL_RATE FROM EMP A, EMP B
GROUP BY A.DEPTNO, A.ENAME, A.SAL
ORDER BY A.DEPTNO, A.ENAME, A.SAL;

