SELECT ENAME, JOB FROM EMP
WHERE DEPTNO = (SELECT DEPTNO FROM EMP WHERE ENAME = 'SMITH');
-- 서브쿼리를 모른다면 쿼리문을 2번 사용해서 DEPTNO를 알 수 있는 쿼리를 작성해야 함
-- 알면 2번의 코드 실행을 할 필요가 없음
-- 대용량 데이터에서는 성능차이가 날 수도 있음

SELECT ENAME, SAL FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);




SELECT DNAME, LOC FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*) > 3);




SELECT DEPTNO, JOB, ENAME, SAL FROM EMP
WHERE (DEPTNO, JOB) IN (SELECT DEPTNO, JOB FROM EMP GROUP BY DEPTNO, JOB HAVING AVG(SAL) > 2000);



SELECT DEPTNO, ENAME, JOB, SAL, (SELECT ROUND(AVG(SAL),0) FROM EMP S WHERE S.JOB = M.JOB) AS JOB_AVG_SAL
FROM EMP M ORDER BY JOB; -- 이번에는 서브쿼리가 먼저 실행될 수 없음 (Join이 되어있기 때문에, 상관서브쿼리)



SELECT DEPTNO, ENAME, JOB, SAL FROM EMP M
WHERE SAL > (SELECT AVG(SAL) AS AVG_SAL FROM EMP WHERE JOB = M.JOB);


SELECT DEPTNO, ENAME, EMP.JOB, SAL, IV.AVG_SAL
FROM EMP, (SELECT JOB, ROUND(AVG(SAL)) AS AVG_SAL FROM EMP GROUP BY JOB) IV 
WHERE EMP.JOB = IV.JOB AND SAL > IV.AVG_SAL
ORDER BY DEPTNO, SAL DESC;
-- 2차원 구조의 Result Set을 Table처럼
-- 인라인뷰 (FROM 절에 사용된 서브쿼리), 동적으로 생성되고 쿼리문이 끝나면 사라짐


SELECT * FROM (SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL)
WHERE ROWNUM<=5;

SELECT TN.EMPNO, TN.ENAME, TN.SAL FROM (SELECT EMPNO, ENAME, SAL FROM EMP ORDER BY SAL DESC) TN
WHERE ROWNUM<=5;

