DROP TABLE BANK;
CREATE TABLE BANK(
    BANK_CODE VARCHAR2(20) CONSTRAINT BANK_CODE_PK PRIMARY KEY,
    BANK_NAME VARCHAR2(20) CONSTRAINT BANK_NAME_NN NOT NULL
);

DROP TABLE USER_INFO;
CREATE TABLE USER_INFO(
    USER_NO      NUMBER(10) CONSTRAINT USER_INFO_NO_PK      PRIMARY KEY, 
    ID           VARCHAR2(20) CONSTRAINT USER_INFO_ID_NN    NOT NULL, 
    PW           VARCHAR2(20) CONSTRAINT USER_INFO_PW_NN   NOT NULL, 
    USER_NAME    VARCHAR2(20) CONSTRAINT USER_INFO_NAME_NN   NOT NULL, 
    MOBILE_NO    VARCHAR2(20)
);

DROP TABLE ACCOUNT;
CREATE TABLE ACCOUNT(
    ACC_ID NUMBER(10) CONSTRAINT ACC_ID_PK PRIMARY KEY,
    BANK_CODE VARCHAR2(20),
    USER_NO NUMBER(10),
    ACC_NO VARCHAR2(20) CONSTRAINT ACC_NO_UK_NN UNIQUE NOT NULL,
    BALANCE NUMBER(20) CONSTRAINT ACC_BALANCE_NN NOT NULL,
    ACC_PW VARCHAR2(20) CONSTRAINT ACC_PW_NN NOT NULL,
    ACC_NICKNAME VARCHAR2(20),
    CONSTRAINT ACC_BANK_CODE_FK FOREIGN KEY (BANK_CODE) REFERENCES BANK(BANK_CODE),
    CONSTRAINT ACC_USER_NO_FK FOREIGN KEY (USER_NO) REFERENCES USER_INFO(USER_NO)
);


DROP TABLE TRANSFER_LOG;
CREATE TABLE TRANSFER_LOG(
    LOG_NO NUMBER(20) CONSTRAINT TRS_LOG_PK PRIMARY KEY,
    LOG_DATE DATE DEFAULT SYSDATE CONSTRAINT TRS_LOG_DATE_NN NOT NULL,
    SENDING_ACC_ID NUMBER(10),
    RECEIVING_ACC_ID NUMBER(10),
    REMITTANCE NUMBER(20) CONSTRAINT TRS_LOG_MON_NN NOT NULL,
    
    CONSTRAINT TRS_LOG_SENDING_ACC_ID_FK FOREIGN KEY (SENDING_ACC_ID) REFERENCES ACCOUNT(ACC_ID),
    CONSTRAINT TRS_LOG_RECEIVING_ACC_ID_FK FOREIGN KEY (RECEIVING_ACC_ID) REFERENCES ACCOUNT(ACC_ID)
);
    
    
    
SELECT * FROM BANK;
INSERT INTO BANK VALUES('1000','HANA');
INSERT INTO BANK VALUES('2000','SHINHAN');
INSERT INTO BANK VALUES('3000','KB');
INSERT INTO BANK VALUES('4000','WOORI');

INSERT INTO USER_INFO VALUES(1, '9bonseong', '1234', '구본성', '010-4773-9853');
INSERT INTO USER_INFO VALUES(2, 'jjaisson', '1234', '짜이쑨', '010-1234-5678');
INSERT INTO USER_INFO VALUES(3, 'sejinin', '1234', '세지닌', '010-2345-6789');
INSERT INTO USER_INFO VALUES(4, 'choongmanddi', '1234', '충만띠', '010-3456-7890');
INSERT INTO USER_INFO VALUES(5, 'maegwijjeol', '1234', '매귀쩔', '010-4567-8901');

INSERT INTO ACCOUNT VALUES (1, '1000', 1, '111-222-333', 1000000, '1234', '주택청약');
INSERT INTO ACCOUNT VALUES (2, '2000', 2, '444-555-666', 2000000, '4321', '적금');
INSERT INTO ACCOUNT VALUES (3, '3000', 3, '777-888-999', 3000000, '1234', '비트코인');