CREATE OR REPLACE TRIGGER TRG_CHANGE_SAL
BEFORE UPDATE OF SAL ON EMP -- 구문을 실행하기 전에 트리거를 시작 (<-> AFTER)
FOR EACH ROW -- 각각의 ROW마다 트리거 실행 (트리거의 실행 횟수)
BEGIN
    IF ( :NEW.SAL > 9000 ) THEN -- NEW : 참조후 열의 값
        :NEW.SAL := 9000;
    END IF;
END;
/


UPDATE EMP SET SAL = 9500 WHERE EMPNO IN (7839, 7844);
SELECT * FROM EMP WHERE EMPNO IN (7839, 7844);
ROLLBACK;