SELECT HIREDATE, MONTHS_BETWEEN(sysdate, HIREDATE), MONTHS_BETWEEN(HIREDATE, sysdate), TRUNC(MONTHS_BETWEEN(SYSDATE, HIREDATE)) FROM EMP; -- SYSDATE와 HIREDATE 간 월 간격 (절댓값이 아닌, 앞 날짜에서 뒷 날짜를 뺸 값)
SELECT SYSDATE, ADD_MONTHS(SYSDATE, 3), ADD_MONTHS(SYSDATE, -1) FROM DUAL; -- 3개월 증가, 1개월 감소
SELECT SYSDATE, LAST_DAY(SYSDATE), NEXT_DAY(SYSDATE, '일요일'), NEXT_DAY(SYSDATE,1), NEXT_DAY(SYSDATE,2) FROM DUAL; -- 이번달 마지막 날, 다음주 일요일, 다음주 일요일 (숫자로 표현), 다음주 월요일
SELECT SYSDATE, ROUND(SYSDATE), ROUND(SYSDATE, 'YEAR'), ROUND(SYSDATE, 'MONTH'), ROUND(SYSDATE, 'DAY') FROM DUAL; -- 날짜에 대한 반올림 (어느 자리까지 표기할지)
SELECT ROUND(TO_DATE('21/05/05 12:00:00', 'YY/MM/DD HH24:MI:SS'),'DAY') FROM DUAL; -- DAY에 대한 반올림은 수요일 12시를 기준으로 잡음
SELECT SYSDATE, TRUNC(SYSDATE, 'YEAR'), TRUNC(SYSDATE, 'MONTH'), TRUNC(SYSDATE, 'DAY'), TRUNC(SYSDATE) FROM DUAL; -- 날짜에 대한 절삭 (어느 자리까지 표기할지)




SELECT
    TO_CHAR(SYSDATE, 'MM"월"DD"일"') AS MMDD1,
    TO_CHAR(SYSDATE, 'MM')||'월'||TO_CHAR(SYSDATE,'DD')||'일' AS MMDD2
FROM DUAL; -- SYSDATE에 대한 포맷 설정

SELECT
    EXTRACT(YEAR FROM SYSDATE),
    EXTRACT(MONTH FROM SYSDATE),
    EXTRACT(DAY FROM SYSDATE)
FROM DUAL; -- SYSDATE 에서 년 월 일 추출

SELECT TO_CHAR(SYSDATE, 'DDD'), TO_CHAR(SYSDATE, 'DD'), TO_CHAR(SYSDATE,'D') FROM DUAL;
--- DDD : 126 (올해 126번째 날) / DD : 06 (해당 월의 일자) / D : 5 (오늘의 요일)


ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN'; -- 모든 출력은 영어권 기준으로 함
SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'YEAR'),
    TO_CHAR(SYSDATE, 'Year'), -- TWENTY TWENTY-ONE (영어권 대문자 표기)
    TO_CHAR(SYSDATE, 'YYYY'), -- TWENTY TWENTY-ONE (영어권 소문자 표기)
    TO_CHAR(SYSDATE, 'YY')
FROM DUAL;    

SELECT
    TO_CHAR(SYSDATE, 'MONTH'), -- 월에 대한 전체 이름
    TO_CHAR(SYSDATE, 'Month'), -- 월에 대한 전체 이름 (첫 글자만 대문자, 나머지는 소문자)
    TO_CHAR(SYSDATE,'MON'), -- 월에 대한 3글자
    TO_CHAR(SYSDATE, 'Mon'), -- 월에 대한 3글자 (첫 글자만 대문자, 나머지는 소문자)
    TO_CHAR(SYSDATE, 'mon'), -- 월에 대한 3글자 (소문자)
    TO_CHAR(SYSDATE,'MM'), -- 숫자형 문자
    TO_CHAR(SYSDATE,'mm') -- 숫자형 문자2
    FROM DUAL;

SELECT SYSDATE,
    TO_CHAR(SYSDATE, 'DAY'), -- 요일 (대문자)
    TO_CHAR(SYSDATE, 'Day'), -- 요일 (첫 글자만 대문자, 나머지는 소문자)
    TO_CHAR(SYSDATE, 'DY'), -- 요일 3글자 (대문자)
    TO_CHAR(SYSDATE, 'dy'), -- 요일 3글자 (첫 글자만 대문자, 나머지는 소문자)
    TO_CHAR(SYSDATE, 'DD'), -- 요일 숫자로 리턴
    TO_CHAR(SYSDATE, 'dd') -- 요일 숫자로 리턴
    FROM DUAL;    

SELECT 123456,
    TO_CHAR(123456,'999999'),
    LENGTH(TO_CHAR(123456, '999999')), -- 부호를 표기하기 때문에 길이가 7
    LENGTH(TO_CHAR(123456, 'fm999999')) -- 공백제거
    FROM DUAL;
    
SELECT TO_CHAR(12345*123.45, '999,999.99'), -- 자리수 내 표기할 수 없기 때문에 999,999.99의 자릿수인 10 만큼 # 표기
    TO_CHAR(12345*123.45, '99,999,999.99') FROM DUAL;    

SELECT TO_CHAR(SAL, '$999,999'),
    REPLACE(TO_CHAR(SAL, '$999,999'), ' ', '?'),
    TO_CHAR(SAL, 'L999,999'), -- NLS_CURRENCY : ￦ (원)
    TO_CHAR(SAL, '999,999'),
    TO_CHAR(SAL,'fm999,999L')
    FROM EMP;
    
SELECT 0012345600,
    TO_CHAR(0012345600,'999999999'), -- 자릿수 내에서 표기
    TO_CHAR(0012345600,'000000000') -- 자릿수 내에서 표기하고 자릿수가 남으면 0
    FROM DUAL;

SELECT * FROM NLS_SESSION_PARAMETERS;
ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN';
ALTER SESSION SET NLS_LANGUAGE = 'KOREAN';


SELECT MIN(ENAME), MAX(ENAME), MIN(SAL), MAX(SAL), MIN(HIREDATE), MAX(HIREDATE) FROM EMP;

SELECT COUNT(*), -- COUMT(*) : 테이블 내 ROW 갯수
    COUNT(EMPNO), -- COUMT(EMPNO) : EMPNO 컬럼 내 데이터 갯수
    COUNT(MGR),
    COUNT(COMM)FROM EMP; 

SELECT COUNT(*),
    SUM(COMM),
    SUM(COMM)/COUNT(*),
    AVG(COMM),
    SUM(COMM)/COUNT(COMM) FROM EMP;

SELECT SUM(COMM),
    SUM(NVL(COMM, 0)), -- NULL 은 연산 무시
    NVL(SUM(COMM),0) FROM EMP;






SELECT DEPTNO, COUNT(*), AVG(SAL) FROM EMP
GROUP BY DEPTNO;

SELECT JOB, COUNT(*), AVG(SAL) FROM EMP
GROUP BY JOB;

SELECT DEPTNO, COUNT(*), AVG(SAL) FROM EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT COMM, COUNT(*) FROM EMP
GROUP BY COMM; -- GROUP BY는 NULL도 처리


-- SELECT JOB, COUNT(*), SUM(SAL), AVG(SAL) FROM EMP GROUP BY DEPTNO; -- 에러
SELECT JOB, COUNT(*), SUM(SAL), AVG(SAL) FROM EMP GROUP BY DEPTNO, JOB;



-- 과제
SELECT TO_CHAR(SYSDATE, 'YY-MM-DD PM HH:MI:SS'), TO_CHAR(SYSDATE, 'YY-MM-DD PM HH:MI:SSSSS')
FROM DUAL;

SELECT TO_CHAR(systimestamp,'HH:MI:SS.FF2'),
    TO_CHAR(systimestamp,'HH:MI:SS.FF9') FROM DUAL;

ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN'; 
ALTER SESSION SET NLS_LANGUAGE = 'KOREAN';

SELECT TO_CHAR(SYSDATE, 'YEAR'),
    TO_CHAR(SYSDATE, 'Year') FROM DUAL;





SELECT COUNT(CASE WHEN DEPTNO=10 THEN DEPTNO END) AS "10번 부서",
    COUNT(CASE WHEN DEPTNO=20 THEN DEPTNO END) AS "20번 부서",
    COUNT(CASE WHEN DEPTNO=30 THEN DEPTNO END) AS "30번 부서"
FROM EMP;

SELECT SUM(DECODE(DEPTNO,10,1,0)) AS "10번 부서",
    SUM(DECODE(DEPTNO,20,1,0)) AS "20번 부서",
    SUM(DECODE(DEPTNO,30,1,0)) AS "30번 부서"
FROM EMP;


SELECT SUM(COUNT(CASE WHEN DEPTNO=10 THEN DEPTNO END)) "10번 부서",
       SUM(COUNT(CASE WHEN DEPTNO=20 THEN DEPTNO END)) "20번 부서",
       SUM(COUNT(CASE WHEN DEPTNO=30 THEN DEPTNO END)) "30번 부서"
FROM EMP
GROUP BY DEPTNO;

SELECT MAX(COUNT(CASE WHEN DEPTNO=10 THEN DEPTNO END)) AS "10번 부서",
    MAX(COUNT(CASE WHEN DEPTNO=20 THEN DEPTNO END)) AS "20번 부서",
    MAX(COUNT(CASE WHEN DEPTNO=30 THEN DEPTNO END)) AS "30번 부서"
FROM EMP
GROUP BY DEPTNO;



ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/YY';

SELECT * FROM EMP WHERE HIREDATE LIKE '82%';


SELECT * FROM EMP
WHERE HIREDATE>=TO_DATE('81-01-01', 'YYYY-MM-DD') AND HIREDATE<=TO_DATE('1981-12-31', 'YYYY-MM-DD');

SELECT * FROM EMP
WHERE HIREDATE BETWEEN TO_DATE('1981-01-01', 'YYYY-MM-DD') AND TO_DATE('1981-12-31', 'YYYY-MM-DD');

SELECT * FROM EMP WHERE 1982 = EXTRACT(YEAR FROM HIREDATE);



SELECT
    CASE WHEN TO_CHAR(LAST_DAY(SYSDATE),'D') = 1 THEN LAST_DAY(SYSDATE)-2
        WHEN TO_CHAR(LAST_DAY(SYSDATE),'D') = 7 THEN LAST_DAY(SYSDATE)-1
        ELSE LAST_DAY(SYSDATE)
    END AS WORKDAY
FROM DUAL;



ALTER SESSION SET NLS_LANGUAGE = 'AMERICAN'; 

SELECT * FROM EMP
WHERE HIREDATE BETWEEN TO_DATE('1981-01-01', 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = KOREAN') AND TO_DATE('1981-12-31', 'YYYY-MM-DD', 'NLS_DATE_LANGUAGE = KOREAN');

ALTER SESSION SET NLS_LANGUAGE = "KOREAN";
ALTER SESSION SET NLS_DATE_FORMAT = 'YY/MM/DD';
ALTER SESSION SET NLS_TERRITORY = 'KOREAN';
SELECT * FROM NLS_SESSION_PARAMETERS;

SELECT HIREDATE FROM EMP;
SELECT TO_DATE ('1950-06-02','YYYY-MM-DD', 'NLS_DATE_LANGUAGE = KOREAN') FROM DUAL;



SELECT * FROM EMP;

ALTER SESSION SET NLS_TERRITORY = "KOREAN";

ALTER SESSION SET NLS_TERRITORY = "KOREA";
ALTER SESSION SET NLS_LANGUAGE = "KOREAN";
ALTER SESSION SET NLS_TERRITORY = "AMERICA";
ALTER SESSION SET NLS_LANGUAGE = "AMERICAN";

SELECT * FROM EMP WHERE HIREDATE LIKE '82%';
SELECT * FROM EMP;

SELECT * FROM EMP
    WHERE HIREDATE
    BETWEEN TO_DATE('1981-01-01', 'YYYY-MM-DD')
    AND TO_DATE('1981-12-31', 'YYYY-MM-DD');

SELECT * FROM EMP
    WHERE HIREDATE
    BETWEEN TO_DATE('1981-1월-01', 'YYYY-MON-DD', 'NLS_DATE_LANGUAGE = KOREAN')
    AND TO_DATE('1981-DEC-31', 'YYYY-MON-DD', 'NLS_DATE_LANGUAGE = AMERICAN');

SELECT TO_DATE(
    'January 15, 1989, 11:00 A.M.',
    'Month dd, YYYY, HH:MI A.M.',
     'NLS_DATE_LANGUAGE = American')
     FROM DUAL;
     
SELECT TO_DATE('January 15, 1989, 11:00 A.M.', 'Month DD, YYYY, HH:MI A.M.', 'NLS_DATE_LANGUAGE=AMERICAN') FROM DUAL;