DROP TABLE CUST;
CREATE TABLE CUST(
    ID  VARCHAR2(8),
    PWD CHAR(8),
    SEX CHAR(1)
);

INSERT INTO CUST VALUES('XMAN', 'XMAN', 'M');
INSERT INTO CUST(ID, PWD, SEX) VALUES('ORACLE', 'OCM', 'F');

SELECT * FROM CUST;

SELECT ID, LENGTH(ID), VSIZE(ID), PWD, LENGTH(PWD), VSIZE(PWD) FROM CUST;
-- VARCHAR는 가변길이라 VSIZE가 다른데, CHAR는 고정길이라 VSIZE가 모두 같음

SELECT * FROM CUST WHERE ID = 'XMAN '; -- VARCHAR2 타입은 BLACK PADDING을 하지 않기 때문에 검색이 안되지만
SELECT * FROM CUST WHERE PWD = 'XMAN '; -- CHAR 타입은 BLANK PADDING을 하기 때문에 결과가 나옴


SELECT * FROM CUST WHERE ID = SUBSTR('XMAN',1,2)||SUBSTR('XMAN',3,2);
SELECT * FROM CUST WHERE PWD = SUBSTR('XMAN',1,2)||SUBSTR('XMAN',3,2); -- SUBSTR 조차 VARCHAR2타입이기 때문에 정확하게 같아야함

SELECT * FROM CUST WHERE PWD LIKE SUBSTR('XMAN',1,2)||SUBSTR('XMAN',3,2)||'%';



DROP TABLE TST_NUMBER;
CREATE TABLE TST_NUMBER(
    NUM NUMBER,
    AGE NUMBER(3)   DEFAULT 19,
    TAX NUMBER(7,2)
);

INSERT INTO TST_NUMBER VALUES(123.5, 123.5, 123.5); -- AGE에 대해 반올림
INSERT INTO TST_NUMBER VALUES(123, 123, 123);
INSERT INTO TST_NUMBER VALUES(123, 12345, 123); -- 정수 자릿수가 맞지 않기 때문에 에러
INSERT INTO TST_NUMBER VALUES(123, '123', 123.56789); -- AGE에 대해 암시적 데이터 형변환
INSERT INTO TST_NUMBER(NUM, TAX) VALUES(456,456); -- AGE에 대해 기본값 19 (명시적 방법)

SELECT * FROM TST_NUMBER;



DROP TABLE TST_DATE;

CREATE TABLE TST_DATE(
    CHAR_HIREDATE   VARCHAR2(8),
    DATE_HIREDATE   DATE,
    LOG_DATE    DATE    DEFAULT SYSDATE);
    
INSERT INTO TST_DATE(CHAR_HIREDATE, DATE_HIREDATE) VALUES(TO_CHAR(SYSDATE,'YYYYMMDD'), SYSDATE);
INSERT INTO TST_DATE(CHAR_HIREDATE, DATE_HIREDATE) VALUES('19990921', TO_DATE('990921', 'YYMMDD'));

SELECT * FROM TST_DATE;


ALTER TABLE TST_DATE ADD(NAME  VARCHAR2(20), AGE NUMBER(3));
DESC TST_DATE;

ALTER TABLE TST_DATE DROP COLUMN AGE;
DESC TST_DATE;


SHOW USER;


SELECT COUNT(*) FROM DBA_OBJECTS;


CREATE TABLE DROP_TBL AS SELECT * FROM LARGE_TBL;
CREATE TABLE TRUNCATE_TBL AS SELECT * FROM LARGE_TBL;
CREATE TABLE DELETE_TBL AS SELECT * FROM LARGE_TBL;


SET TIMING ON

DROP TABLE DROP_TBL;

TRUNCATE TABLE TRUNCATE_TBL;

DELETE FROM DELETE_TBL;
ROLLBACK;

SELECT COUNT(*) FROM DELETE_TBL;

ALTER TABLE DELETE_TBL ADD(ADDR VARCHAR2(60));
ALTER TABLE DELETE_TBL ADD(AGE  NUMBER(3) DEFAULT 18); 

SELECT * FROM DELETE_TBL WHERE ROWNUM < 10;

DROP TABLE DELETE_TBL;
DROP TABLE TRUNCATE_TBL;
DROP TABLE DROP_TBL;


SELECT RPAD(ENAME, 10, '')||'@@' FROM EMP;
SELECT RPAD(ENAME, 10, ' ')||'@@' FROM EMP;




SELECT TABLESPACE_NAME, SUM(BYTES)/1024/1024 AS FREE_SPACE_M FROM DBA_FREE_SPACE GROUP BY TABLESPACE_NAME;
SELECT SEGMENT_NAME, BYTES/1024/1024 AS SIZE_MEGA FROM DBA_SEGMENTS WHERE TABLESPACE_NAME = 'USERS' ORDER BY 2 DESC;


SELECT A.DEPTNO, A.ENAME, A.SAL, ROUND(A.SAL/SUM(B.SAL),4)*100 FROM EMP A, EMP B
GROUP BY A.DEPTNO, A.ENAME, A.SAL;

SELECT * FROM CUSTOMER;