-- 싱글컬럼
SELECT ENAME, SAL FROM EMP WHERE SAL < (SELECT AVG(SAL) FROM EMP);

-- 싱글컬럼, 멀티로우
SELECT DNAME, LOC FROM DEPT
WHERE DEPTNO IN (SELECT DEPTNO FROM EMP GROUP BY DEPTNO HAVING COUNT(*)>3);

--MULTIPLE COLUMN, MULTIPLE ROW RETURN
SELECT DEPTNO, JOB, ENAME, SAL FROM EMP
WHERE (DEPTNO, JOB) IN (SELECT DEPTNO, JOB FROM EMP GROUP BY DEPTNO, JOB HAVING AVG(SAL) > 2000);

-- Scalar Subquery
SELECT DEPTNO, ENAME, JOB, SAL, (SELECT ROUND(AVG(SAL),0) FROM EMP E2 WHERE E.DEPTNO = E2.DEPTNO) AS AVG_SAL
FROM EMP E ORDER BY DEPTNO;

-- 인라인뷰
SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL, E2.AVG_SAL
FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL),0) AS AVG_SAL FROM EMP GROUP BY DEPTNO) E2
WHERE E.DEPTNO = E2.DEPTNO ORDER BY DEPTNO;


SELECT E.DEPTNO, E.ENAME, E.JOB, E.SAL, E2.AVG_SAL
FROM EMP E, (SELECT DEPTNO, ROUND(AVG(SAL),0) AS AVG_SAL FROM EMP GROUP BY DEPTNO) E2
WHERE E.DEPTNO = E2.DEPTNO ORDER BY DEPTNO
;

