/*
BEGIN
    CREATE TABLE BY_DANAMIC(X DATE); -- 에러
END;
/
-- PL/SQL BLOCK 내에서 DDL, DCL 등의 계열은 동적으로만 가능
*/

DECLARE
    V_SQL   VARCHAR2(2000);
BEGIN
    BEGIN
        V_SQL := 'DROP TABLE BY_DYNAMIC';
        EXECUTE IMMEDIATE V_SQL; -- 변수에 SQL 문장 저장 후 실행
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('DYNAMIC SQL DROP => '||SUBSTR(SQLERRM, 1, 50));
    END;
    
    BEGIN
        EXECUTE IMMEDIATE 'CREATE TABLE BY_DYNAMIC(X DATE)';
    EXCEPTION
        WHEN OTHERS THEN
            DBMS_OUTPUT.PUT_LINE('DYNAMIC SQL CREATE =>'||SUBSTR(SQLERRM, 1, 50));
    END;
END;
/

DESC BY_DYNAMIC;
        