--3. LOCAL DB 계정 (CLIENT) ? 서버실 계정 (SERVER)
--- 클라이언트

CREATE DATABASE LINK TLINK3 CONNECT TO DA2103 IDENTIFIED BY "da03" USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.217.202)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=KOPODA)
 )
)';


INSERT INTO SERVER_TABLE2@TLINK3 VALUES (4,'test4');
INSERT INTO SERVER_TABLE2@TLINK3 VALUES (5,'test5');
INSERT INTO SERVER_TABLE2@TLINK3 VALUES (6, 'test6');


COMMIT;

SELECT * FROM SERVER_TABLE2@TLINK3;

