--1. LOCAL DB DBA 계정 (CLIENT) - 서버실 (SERVER)
--- 서버

CREATE TABLE SERVER_TABLE (
    VAR1 NUMBER(4) ,
    VAR2 VARCHAR(32)
);

DROP TABLE SERVER_TABLE;

INSERT INTO SERVER_TABLE VALUES (1,'test');
INSERT INTO SERVER_TABLE VALUES (2,'test2');
INSERT INTO SERVER_TABLE VALUES (3, 'test3');

SELECT * FROM SERVER_TABLE@TLINK;
select * from server_table;


BEGIN
    UPDATE SERVER_TABLE@TLINK SET VAR1 = 10 WHERE VAR2='test';
    UPDATE SERVER_TABLE SET VAR1 = 10 WHERE VAR2='test';
    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
    ROLLBACK;
END;    
    

COMMIT;



--2. LOCAL DB DBA 계정 (SERVER) - 서버실 (CLIENT)
--- 클라이언트


CREATE DATABASE LINK TLINK2 CONNECT TO scott IDENTIFIED BY tiger USING
'(DESCRIPTION=
 (ADDRESS_LIST=
  (ADDRESS=(PROTOCOL=TCP)(HOST=192.168.119.119)(PORT=1521))
 )
 (CONNECT_DATA=
 (SERVICE_NAME=DINK)
 )
)';

--3. LOCAL DB 계정 (CLIENT) ? 서버실 계정 (SERVER)
--- 서버


CREATE TABLE SERVER_TABLE2 (
    VAR1 NUMBER(4) ,
    VAR2 VARCHAR(32)
);

INSERT INTO SERVER_TABLE2 VALUES (1,'test');
INSERT INTO SERVER_TABLE2 VALUES (2,'test2');
INSERT INTO SERVER_TABLE2 VALUES (3, 'test3');

COMMIT;

--4. 분산 트랜잭션 구현
