DECLARE
    V_NUM1  NUMBER(4,2);
    V_NUM2  NUMBER(4,2) := 30;
BEGIN
    IF(NVL(V_NUM1>1,TRUE) AND V_NUM2<31) THEN
        DBMS_OUTPUT.PUT_LINE('(V_NUM1 > 1 AND V_NUM2<31) IS TRUE');
    ELSIF NOT (V_NUM1 > 1 AND V_NUM2 < 31) THEN
        DBMS_OUTPUT.PUT_LINE('(V_NUM1 > 1 AND V_NUM2<31) IS FALSE'); -- NULL AND TRUE -> NULL
    ELSE
        DBMS_OUTPUT.PUT_LINE('NOT TRUE, NOT FALSE....');
    END IF;
END;    
    
    