DECLARE
    LOOP_INDEX  NUMBER(4)   :=  1;
    MAX_LOOP_INDEX  NUMBER(4):= 30;
BEGIN
    LOOP
        DBMS_OUTPUT.PUT_LINE('LOOP COUNT => '||TO_CHAR(LOOP_INDEX));
        LOOP_INDEX  :=  LOOP_INDEX+1;
        EXIT WHEN MAX_LOOP_INDEX < LOOP_INDEX;
    END LOOP;
END;    