/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-06 06:46:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.card;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class cardlist_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/spring-webmvc-5.3.9.jar!/META-INF/spring-form.tld", Long.valueOf(1626212264000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629856867447L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.9.jar", Long.valueOf(1629856868866L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("<title>Job Board</title>\r\n");
      out.write("<meta name=\"description\" content=\"\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("	href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ pageContext.request.contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/custom/modal.css\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("		$('#modalBtn').click(function() {\r\n");
      out.write("			$('.index_modal').css('display', 'block')\r\n");
      out.write("			$('body').css(\"overflow\", \"hidden\");\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("		//모달 다시 숨기기\r\n");
      out.write("		$('.index_modal_cancel').click(function() {\r\n");
      out.write("			$('.index_modal').css('display', 'none')\r\n");
      out.write("			$('body').css(\"overflow\", \"scroll\");\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		temp = []\r\n");
      out.write("		amount_temp = []\r\n");
      out.write("\r\n");
      out.write("		$(\"input[class=form-check-input]\").each(function(idx) {\r\n");
      out.write("\r\n");
      out.write("			var value = $(this).val();\r\n");
      out.write("			temp.push(\"#\" + value + \"_slider-range\");\r\n");
      out.write("			amount_temp.push(\"#\" + value + \"_amount\");\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("		for (var i = 0; i < temp.length; i++) {\r\n");
      out.write("\r\n");
      out.write("			eval('$(function(){$(temp['\r\n");
      out.write("					+ i\r\n");
      out.write("					+ ']).slider({range:true,min:0,step:1,max:50,values:[0,50],slide:function(event,ui){$(amount_temp['\r\n");
      out.write("					+ i\r\n");
      out.write("					+ ']).val(ui.values[0]+\" % - \"+ui.values[1]+\" %\")}});$(amount_temp['\r\n");
      out.write("					+ i + ']).val($(temp[' + i\r\n");
      out.write("					+ ']).slider(\"values\",0)+\" % - \"+$(temp[' + i\r\n");
      out.write("					+ ']).slider(\"values\",1)+\" %\")});')\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$('#searchBtn').click(function() {\r\n");
      out.write("			getCardList();\r\n");
      out.write("		})	\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		\r\n");
      out.write("		function getCardList() {\r\n");
      out.write("			\r\n");
      out.write("			let benefitInputList = [];\r\n");
      out.write("\r\n");
      out.write("			$(\"input[class=form-check-input]:checked\").each(function(idx) {\r\n");
      out.write("				var value = $(this).val();\r\n");
      out.write("				benefitInputList.push(value);\r\n");
      out.write("\r\n");
      out.write("			})\r\n");
      out.write("\r\n");
      out.write("			console.log(\"benefitInputList : \" + benefitInputList)\r\n");
      out.write("\r\n");
      out.write("			var json_data = {}\r\n");
      out.write("\r\n");
      out.write("			json_data['cardName'] = $(\"#cardName\").val();\r\n");
      out.write("			json_data['cardType'] = $(\"#cardType\").val();\r\n");
      out.write("			json_data['annualFeeType'] = $(\"#annualFeeType\").val()\r\n");
      out.write("			json_data['annualFeeRange'] = $(\"#amount\").val()\r\n");
      out.write("\r\n");
      out.write("			console.log(json_data)\r\n");
      out.write("			\r\n");
      out.write("			for(var i = 0; i<benefitInputList.length; i++){\r\n");
      out.write("				json_data[benefitInputList[i]]=document.getElementById(benefitInputList[i]+\"_amount\").value\r\n");
      out.write("				console.log(json_data)\r\n");
      out.write("			}\r\n");
      out.write("			console.log(json_data)\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				'type' : 'post',\r\n");
      out.write("				'contentType' : \"application/json; charset=utf-8\",\r\n");
      out.write("				'url' : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/cardlist',\r\n");
      out.write("				'data' : JSON.stringify(\r\n");
      out.write("					json_data\r\n");
      out.write("		\r\n");
      out.write("				),\r\n");
      out.write("				\r\n");
      out.write("				'success' : function(data) {\r\n");
      out.write("					console.log(\"석세스\")\r\n");
      out.write("		\r\n");
      out.write("				},\r\n");
      out.write("				'error' : function() {\r\n");
      out.write("					console.log(\"실패\")\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	})\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	function annualFeeChange(e) {\r\n");
      out.write("		var div = document.getElementById('annualFeeRangeDiv');\r\n");
      out.write("		if ($(\"#annualFeeType\").val() == 'Y') {\r\n");
      out.write("			div.style.display = 'block';\r\n");
      out.write("		} else {\r\n");
      out.write("			div.style.display = 'none';\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("\r\n");
      out.write("	function getBenefitList() {\r\n");
      out.write("		let allBenefitList = [];\r\n");
      out.write("		let benefitInputList = [];\r\n");
      out.write("\r\n");
      out.write("		$(\"input[class=form-check-input]\").each(function(idx) {\r\n");
      out.write("\r\n");
      out.write("			var value = $(this).val();\r\n");
      out.write("			allBenefitList.push(value);\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("		$(\"input[class=form-check-input]:checked\").each(function(idx) {\r\n");
      out.write("\r\n");
      out.write("			var value = $(this).val();\r\n");
      out.write("			benefitInputList.push(value);\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("\r\n");
      out.write("		for (i = 0; i < benefitInputList.length; i++) {\r\n");
      out.write("\r\n");
      out.write("			allBenefitList = allBenefitList.filter(function(item) {\r\n");
      out.write("				return item !== benefitInputList[i];\r\n");
      out.write("\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		for (i = 0; i < benefitInputList.length; i++) {\r\n");
      out.write("			document.getElementById(benefitInputList[i]).style.display = 'block'\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		for (i = 0; i < allBenefitList.length; i++) {\r\n");
      out.write("			document.getElementById(allBenefitList[i]).style.display = 'none'\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		\r\n");
      out.write("\r\n");
      out.write("	}\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("	<header>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- bradcam_area  -->\r\n");
      out.write("	<div class=\"bradcam_area bradcam_bg_1\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-xl-12\">\r\n");
      out.write("					<div class=\"bradcam_text\">\r\n");
      out.write("						<h3>나만의 카드</h3>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!--/ bradcam_area  -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- job_listing_area_start  -->\r\n");
      out.write("	<div class=\"job_listing_area plus_padding\">\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div class=\"row\">\r\n");
      out.write("				<div class=\"col-lg-3\">\r\n");
      out.write("					<div class=\"job_filter white-bg\">\r\n");
      out.write("						<form name=\"benefitInputForm\">\r\n");
      out.write("							<div class=\"form_inner white-bg\">\r\n");
      out.write("								<h3>Filter</h3>\r\n");
      out.write("								<div class=\"row\">\r\n");
      out.write("									<div class=\"col-lg-12\">\r\n");
      out.write("										<div class=\"single_field\">\r\n");
      out.write("											<input type=\"text\" id=\"cardName\" name=\"cardName\"\r\n");
      out.write("												placeholder=\"카드 이름 입력\">\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-lg-12\">\r\n");
      out.write("										<div class=\"single_field\">\r\n");
      out.write("											<select class=\"wide\" id=\"cardType\" name=\"cardType\">\r\n");
      out.write("												<option value=\"\">카드 종류 선택</option>\r\n");
      out.write("												<option value=\"CREDIT\">신용카드</option>\r\n");
      out.write("												<option value=\"CHECK\">체크카드</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-lg-12\">\r\n");
      out.write("										<div class=\"single_field\">\r\n");
      out.write("											<select class=\"wide\" id=\"annualFeeType\"\r\n");
      out.write("												onchange=\"annualFeeChange(this)\" name=\"annualFeeType\">\r\n");
      out.write("												<option data-display=\"ALL\" value=\"\">연회비 유무 선택</option>\r\n");
      out.write("												<option value=\"Y\">연회비 있음</option>\r\n");
      out.write("												<option value=\"N\">연회비 없음</option>\r\n");
      out.write("											</select>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"col-lg-12\" id=\"annualFeeRangeDiv\"\r\n");
      out.write("										style=\"display: none\">\r\n");
      out.write("										<div class=\"range_wrap\">\r\n");
      out.write("											<label for=\"amount\">연회비 범위 : </label>\r\n");
      out.write("											<div id=\"slider-range\"></div>\r\n");
      out.write("											<p>\r\n");
      out.write("												<input type=\"text\" id=\"amount\" readonly\r\n");
      out.write("													style=\"border: 0; color: #7A838B; font-size: 14px; font-weight: 400;\"\r\n");
      out.write("													name=\"annualFeeRange\">\r\n");
      out.write("											</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("									<div class=\"col-lg-12\">\r\n");
      out.write("										<button type=\"button\" class=\"genric-btn success medium\"\r\n");
      out.write("											id=\"modalBtn\">혜택 추가/변경</button>\r\n");
      out.write("									</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("									");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("							<div class=\"reset_btn\">\r\n");
      out.write("								<button type=\"button\" class=\"boxed-btn3 w-100\" id=\"searchBtn\">검색</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"col-lg-9\">\r\n");
      out.write("					<div class=\"recent_joblist_wrap\">\r\n");
      out.write("						<div class=\"recent_joblist white-bg \">\r\n");
      out.write("							<div class=\"row align-items-center\">\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<h4>Job Listing</h4>\r\n");
      out.write("								</div>\r\n");
      out.write("								<div class=\"col-md-6\">\r\n");
      out.write("									<div class=\"serch_cat d-flex justify-content-end\">\r\n");
      out.write("										<select>\r\n");
      out.write("											<option data-display=\"Most Recent\">혜택이 많은 순</option>\r\n");
      out.write("											<option value=\"1\">최다 선택순</option>\r\n");
      out.write("											<option value=\"2\">연령별</option>\r\n");
      out.write("											<option value=\"4\">Designer</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("					<div class=\"job_lists m-0\">\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-12 col-md-12\">\r\n");
      out.write("								<div class=\"single_jobs white-bg d-flex justify-content-between\">\r\n");
      out.write("									<div class=\"jobs_left d-flex align-items-center\">\r\n");
      out.write("										<div class=\"thumb\">\r\n");
      out.write("											<img src=\"img/svg_icon/1.svg\" alt=\"\">\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"jobs_conetent\">\r\n");
      out.write("											<a href=\"job_details.html\"><h4>Software Engineer</h4></a>\r\n");
      out.write("											<div class=\"links_locat d-flex align-items-center\">\r\n");
      out.write("												<div class=\"location\">\r\n");
      out.write("													<p>\r\n");
      out.write("														<i class=\"fa fa-map-marker\"></i> California, USA\r\n");
      out.write("													</p>\r\n");
      out.write("												</div>\r\n");
      out.write("												<div class=\"location\">\r\n");
      out.write("													<p>\r\n");
      out.write("														<i class=\"fa fa-clock-o\"></i> Part-time\r\n");
      out.write("													</p>\r\n");
      out.write("												</div>\r\n");
      out.write("											</div>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("									<div class=\"jobs_right\">\r\n");
      out.write("										<div class=\"apply_now\">\r\n");
      out.write("											<a class=\"heart_mark\" href=\"#\"> <i class=\"fa fa-heart\"></i>\r\n");
      out.write("											</a> <a href=\"job_details.html\" class=\"boxed-btn3\">Apply Now</a>\r\n");
      out.write("										</div>\r\n");
      out.write("										<div class=\"date\">\r\n");
      out.write("											<p>Date line: 31 Jan 2020</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</div>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("\r\n");
      out.write("						</div>\r\n");
      out.write("						<div class=\"row\">\r\n");
      out.write("							<div class=\"col-lg-12\">\r\n");
      out.write("								<div class=\"pagination_wrap\">\r\n");
      out.write("									<ul>\r\n");
      out.write("										<li><a href=\"#\"> <i class=\"ti-angle-left\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("										<li><a href=\"#\"><span>01</span></a></li>\r\n");
      out.write("										<li><a href=\"#\"><span>02</span></a></li>\r\n");
      out.write("										<li><a href=\"#\"> <i class=\"ti-angle-right\"></i>\r\n");
      out.write("										</a></li>\r\n");
      out.write("									</ul>\r\n");
      out.write("								</div>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- job_listing_area_end  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- footer start -->\r\n");
      out.write("\r\n");
      out.write("	<!--/ footer end  -->\r\n");
      out.write("\r\n");
      out.write("	<!-- link that opens popup -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		$(function() {\r\n");
      out.write("			$(\"#slider-range\")\r\n");
      out.write("					.slider(\r\n");
      out.write("							{\r\n");
      out.write("								range : true,\r\n");
      out.write("								min : 0,\r\n");
      out.write("								step : 10000,\r\n");
      out.write("								max : 250000,\r\n");
      out.write("								values : [ 0, 250000 ],\r\n");
      out.write("								slide : function(event, ui) {\r\n");
      out.write("									$(\"#amount\").val(\r\n");
      out.write("											ui.values[0] + \"원 - \"\r\n");
      out.write("													+ ui.values[1] + \"원\");\r\n");
      out.write("								}\r\n");
      out.write("							});\r\n");
      out.write("\r\n");
      out.write("			$(\"#amount\").val(\r\n");
      out.write("					$(\"#slider-range\").slider(\"values\", 0) + \"원 - \"\r\n");
      out.write("							+ $(\"#slider-range\").slider(\"values\", 1) + \"원\");\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		/* 여기서부터 시작 */\r\n");
      out.write("\r\n");
      out.write("		/* temp = [ '#CAFE_BAKERY_slider-range', '#FINANCE_slider-range' ]\r\n");
      out.write("		amount_temp = [ '#CAFE_BAKERY_amount', '#FINANCE_amount' ] */\r\n");
      out.write("\r\n");
      out.write("		/* $(function() {\r\n");
      out.write("			$(temp[0]).slider(\r\n");
      out.write("					{\r\n");
      out.write("						range : true,\r\n");
      out.write("						min : 0,\r\n");
      out.write("						step : 1000,\r\n");
      out.write("						max : 24600,\r\n");
      out.write("						values : [ 750, 24600 ],\r\n");
      out.write("						slide : function(event, ui) {\r\n");
      out.write("							$(amount_temp[0]).val(\r\n");
      out.write("									\"$\" + ui.values[0] + \" - $\" + ui.values[1]\r\n");
      out.write("											+ \"/ Year\");\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("			$(amount_temp[0])\r\n");
      out.write("					.val(\r\n");
      out.write("							\"$\" + $(temp[0]).slider(\"values\", 0)\r\n");
      out.write("									+ \" - $\"\r\n");
      out.write("									+ $(temp[0]).slider(\"values\", 1)\r\n");
      out.write("									+ \"/ Year\");\r\n");
      out.write("		});\r\n");
      out.write("		 */\r\n");
      out.write("		/* 	for (var i = 0; i < temp.length; i++) {\r\n");
      out.write("\r\n");
      out.write("				eval('$(function(){$(temp['\r\n");
      out.write("						+ i\r\n");
      out.write("						+ ']).slider({range:true,min:0,step:1000,max:24600,values:[750,24600],slide:function(event,ui){$(amount_temp['\r\n");
      out.write("						+ i\r\n");
      out.write("						+ ']).val(\"$\"+ui.values[0]+\" - $\"+ui.values[1]+\"/ Year\")}});$(amount_temp['\r\n");
      out.write("						+ i + ']).val(\"$\"+$(temp[' + i\r\n");
      out.write("						+ ']).slider(\"values\",0)+\" - $\"+$(temp[' + i\r\n");
      out.write("						+ ']).slider(\"values\",1)+\"/ Year\")});')\r\n");
      out.write("			} */\r\n");
      out.write("\r\n");
      out.write("		/* $(function() {\r\n");
      out.write("			$(temp[1]).slider(\r\n");
      out.write("					{\r\n");
      out.write("						range : true,\r\n");
      out.write("						min : 0,\r\n");
      out.write("						step : 1000,\r\n");
      out.write("						max : 24600,\r\n");
      out.write("						values : [ 750, 24600 ],\r\n");
      out.write("						slide : function(event, ui) {\r\n");
      out.write("							$(amount_temp[1]).val(\r\n");
      out.write("									\"$\" + ui.values[0] + \" - $\" + ui.values[1]\r\n");
      out.write("											+ \"/ Year\");\r\n");
      out.write("						}\r\n");
      out.write("					});\r\n");
      out.write("\r\n");
      out.write("			$(amount_temp[1])\r\n");
      out.write("					.val(\r\n");
      out.write("							\"$\" + $(temp[1]).slider(\"values\", 0)\r\n");
      out.write("									+ \" - $\"\r\n");
      out.write("									+ $(temp[1]).slider(\"values\", 1)\r\n");
      out.write("									+ \"/ Year\");\r\n");
      out.write("		}); \r\n");
      out.write("		 */\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("	<script>\r\n");
      out.write("		/* 	let benefitList = [];\r\n");
      out.write("\r\n");
      out.write("		 $(\"input[class=form-check-input]\").each(function(idx) {\r\n");
      out.write("\r\n");
      out.write("		 var value = $(this).val();\r\n");
      out.write("		 benefitList.push(value);\r\n");
      out.write("\r\n");
      out.write("		 }) */\r\n");
      out.write("\r\n");
      out.write("		/* let benefitList = [ \"CAFE_BAKERY\", \"FINANCE\" ];\r\n");
      out.write("\r\n");
      out.write("		sliderVarList = []\r\n");
      out.write("		amountVarList = []\r\n");
      out.write("\r\n");
      out.write("		for (var i = 0; i < benefitList.length; i++) {\r\n");
      out.write("			sliderVarList.push(\"#\" + benefitList[i] + \"_slider_range\")\r\n");
      out.write("			amountVarList.push(\"#\" + benefitList[i] + \"_amount\")\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		console.log(sliderVarList)\r\n");
      out.write("		console.log(amountVarList)\r\n");
      out.write("\r\n");
      out.write("		for (var i = 0; i < sliderVarList.length; i++) {\r\n");
      out.write("\r\n");
      out.write("			$(function() {\r\n");
      out.write("				$(sliderVarList[i]).slider(\r\n");
      out.write("						{\r\n");
      out.write("							range : true,\r\n");
      out.write("							min : 0,\r\n");
      out.write("							step : 1000,\r\n");
      out.write("							max : 24600,\r\n");
      out.write("							values : [ 750, 24600 ],\r\n");
      out.write("							slide : function(event, ui) {\r\n");
      out.write("								$(amountVarList[i]).val(\r\n");
      out.write("										\"$\" + ui.values[0] + \" - $\"\r\n");
      out.write("												+ ui.values[1] + \"/ Year\");\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("\r\n");
      out.write("				$(amountVarList[i]).val(\r\n");
      out.write("						\"$\" + $(sliderVarList[i]).slider(\"values\", 0) + \" - $\"\r\n");
      out.write("								+ $(sliderVarList[i]).slider(\"values\", 1)\r\n");
      out.write("								+ \"/ Year\");\r\n");
      out.write("			});\r\n");
      out.write("\r\n");
      out.write("		} */\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<div class=\"index_modal\">\r\n");
      out.write("		<div class=\"index_body\">\r\n");
      out.write("			<h4 class=\"txt-center\">혜택 리스트</h4>\r\n");
      out.write("			<h6 class=\"txt-center\">원하는 혜택을 선택하세요</h6>\r\n");
      out.write("			<div class=\"content\"></div>\r\n");
      out.write("			<hr>\r\n");
      out.write("\r\n");
      out.write("			<div class=\"select single_field .align-center\">\r\n");
      out.write("\r\n");
      out.write("				<div class=\"single_field\">\r\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					<table class=\"align-center\">\r\n");
      out.write("						");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("					</table>\r\n");
      out.write("\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"mt-30\"></div>\r\n");
      out.write("				<button type=\"button\" class=\"boxed-btn3 index_modal_cancel\"\r\n");
      out.write("					onclick=\"getBenefitList()\">확인</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/card/cardlist.jsp(252,9) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/card/cardlist.jsp(252,9) '${requestScope.benefitList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.benefitList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/card/cardlist.jsp(252,9) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("benefitList");
      // /WEB-INF/jsp/card/cardlist.jsp(252,9) name = varStatus type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVarStatus("loop");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("\r\n");
            out.write("										<div class=\"col-lg-12\" id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("											style=\"display: none\">\r\n");
            out.write("											<div class=\"range_wrap\">\r\n");
            out.write("												<label for=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_amount\">");
            if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write(" 범위 : </label>\r\n");
            out.write("												<div id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_slider-range\"></div>\r\n");
            out.write("												<p>\r\n");
            out.write("													<input type=\"text\" name=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\"\r\n");
            out.write("														id=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("_amount\" readonly\r\n");
            out.write("														style=\"border: 0; color: #7A838B; font-size: 14px; font-weight: 400;\">\r\n");
            out.write("												</p>\r\n");
            out.write("											</div>\r\n");
            out.write("										</div>\r\n");
            out.write("\r\n");
            out.write("									");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvarStatus_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f0_reused = false;
    try {
      _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/card/cardlist.jsp(258,58) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.categoryKor }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
      if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      _jspx_th_c_005fout_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/jsp/card/cardlist.jsp(517,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("i");
      // /WEB-INF/jsp/card/cardlist.jsp(517,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/card/cardlist.jsp(517,5) '0'",_jsp_getExpressionFactory().createValueExpression("0",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/jsp/card/cardlist.jsp(518,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("j");
      // /WEB-INF/jsp/card/cardlist.jsp(518,5) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/card/cardlist.jsp(518,5) '3'",_jsp_getExpressionFactory().createValueExpression("3",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /WEB-INF/jsp/card/cardlist.jsp(520,6) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/card/cardlist.jsp(520,6) '${requestScope.benefitList }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${requestScope.benefitList }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      // /WEB-INF/jsp/card/cardlist.jsp(520,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("benefitList");
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f0(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("							<td class=\"td_input\"><input class=\"form-check-input\"\r\n");
            out.write("								name=\"form-check-input\" type=\"checkbox\"\r\n");
            out.write("								value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.category }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("\" id=\"flexCheckDefault\">\r\n");
            out.write("								");
            if (_jspx_meth_c_005fout_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("</td>\r\n");
            out.write("							");
            if (_jspx_meth_c_005fif_005f1(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("							");
            if (_jspx_meth_c_005fset_005f2(_jspx_th_c_005fforEach_005f1, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f1))
              return true;
            out.write("\r\n");
            out.write("						");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/card/cardlist.jsp(521,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i%j == 0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<tr>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fout_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f1 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    boolean _jspx_th_c_005fout_005f1_reused = false;
    try {
      _jspx_th_c_005fout_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fout_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/card/cardlist.jsp(527,8) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fout_005f1.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ benefitList.categoryKor }", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fout_005f1 = _jspx_th_c_005fout_005f1.doStartTag();
      if (_jspx_th_c_005fout_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f1);
      _jspx_th_c_005fout_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fout_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fout_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/card/cardlist.jsp(528,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${i%j == j-1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<tr>\r\n");
          out.write("							");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f1, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f1)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f2_reused = false;
    try {
      _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f1);
      // /WEB-INF/jsp/card/cardlist.jsp(531,7) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setVar("i");
      // /WEB-INF/jsp/card/cardlist.jsp(531,7) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f2.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/jsp/card/cardlist.jsp(531,7) '${i+1 }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${i+1 }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
      if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      _jspx_th_c_005fset_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f2_reused);
    }
    return false;
  }
}
