/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-09-07 10:41:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.card;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class detail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/KOPO_TIL/JAVA/eclipse-work/wtpwebapps/DynamicCardStatement/WEB-INF/lib/spring-webmvc-5.3.9.jar!/META-INF/spring-form.tld", Long.valueOf(1626212264000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1629856867447L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-5.3.9.jar", Long.valueOf(1629856868866L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html class=\"no-js\" lang=\"zxx\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <meta http-equiv=\"x-ua-compatible\" content=\"ie=edge\">\r\n");
      out.write("    <title>Job Board</title>\r\n");
      out.write("    <meta name=\"description\" content=\"\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("    <header>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/topMenu.jsp", out, false);
      out.write("\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("    <!-- bradcam_area  -->\r\n");
      out.write("    <div class=\"bradcam_area bradcam_bg_1\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-xl-12\">\r\n");
      out.write("                    <div class=\"bradcam_text\">\r\n");
      out.write("                        <h3>Software Engineer</h3>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <!--/ bradcam_area  -->\r\n");
      out.write("\r\n");
      out.write("    <div class=\"job_details_area\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row\">\r\n");
      out.write("                <div class=\"col-lg-8\">\r\n");
      out.write("                    <div class=\"job_details_header\">\r\n");
      out.write("                        <div class=\"single_jobs white-bg d-flex justify-content-between\">\r\n");
      out.write("                            <div class=\"jobs_left d-flex align-items-center\">\r\n");
      out.write("                                <div class=\"thumb\">\r\n");
      out.write("                                    <img src=\"img/svg_icon/1.svg\" alt=\"\">\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"jobs_conetent\">\r\n");
      out.write("                                    <a href=\"#\"><h4>Software Engineer</h4></a>\r\n");
      out.write("                                    <div class=\"links_locat d-flex align-items-center\">\r\n");
      out.write("                                        <div class=\"location\">\r\n");
      out.write("                                            <p> <i class=\"fa fa-map-marker\"></i> California, USA</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"location\">\r\n");
      out.write("                                            <p> <i class=\"fa fa-clock-o\"></i> Part-time</p>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"jobs_right\">\r\n");
      out.write("                                <div class=\"apply_now\">\r\n");
      out.write("                                    <a class=\"heart_mark\" href=\"#\"> <i class=\"ti-heart\"></i> </a>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"descript_wrap white-bg\">\r\n");
      out.write("                        <div class=\"single_wrap\">\r\n");
      out.write("                            <h4>Job description</h4>\r\n");
      out.write("                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>\r\n");
      out.write("                            <p>Variations of passages of lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_wrap\">\r\n");
      out.write("                            <h4>Responsibility</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>The applicants should have experience in the following areas.\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>Have sound knowledge of commercial activities.</li>\r\n");
      out.write("                                <li>Leadership, analytical, and problem-solving abilities.</li>\r\n");
      out.write("                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_wrap\">\r\n");
      out.write("                            <h4>Qualifications</h4>\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>The applicants should have experience in the following areas.\r\n");
      out.write("                                </li>\r\n");
      out.write("                                <li>Have sound knowledge of commercial activities.</li>\r\n");
      out.write("                                <li>Leadership, analytical, and problem-solving abilities.</li>\r\n");
      out.write("                                <li>Should have vast knowledge in IAS/ IFRS, Company Act, Income Tax, VAT.</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"single_wrap\">\r\n");
      out.write("                            <h4>Benefits</h4>\r\n");
      out.write("                            <p>There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing.</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"apply_job_form white-bg\">\r\n");
      out.write("                        <h4>Apply for the job</h4>\r\n");
      out.write("                        <form action=\"#\">\r\n");
      out.write("                            <div class=\"row\">\r\n");
      out.write("                                <div class=\"col-md-6\">\r\n");
      out.write("                                    <div class=\"input_field\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Your name\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-6\">\r\n");
      out.write("                                    <div class=\"input_field\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Email\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"input_field\">\r\n");
      out.write("                                        <input type=\"text\" placeholder=\"Website/Portfolio link\">\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"input-group\">\r\n");
      out.write("                                        <div class=\"input-group-prepend\">\r\n");
      out.write("                                          <button type=\"button\" id=\"inputGroupFileAddon03\"><i class=\"fa fa-cloud-upload\" aria-hidden=\"true\"></i>\r\n");
      out.write("                                          </button>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                        <div class=\"custom-file\">\r\n");
      out.write("                                          <input type=\"file\" class=\"custom-file-input\" id=\"inputGroupFile03\" aria-describedby=\"inputGroupFileAddon03\">\r\n");
      out.write("                                          <label class=\"custom-file-label\" for=\"inputGroupFile03\">Upload CV</label>\r\n");
      out.write("                                        </div>\r\n");
      out.write("                                      </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"input_field\">\r\n");
      out.write("                                        <textarea name=\"#\" id=\"\" cols=\"30\" rows=\"10\" placeholder=\"Coverletter\"></textarea>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                                <div class=\"col-md-12\">\r\n");
      out.write("                                    <div class=\"submit_btn\">\r\n");
      out.write("                                        <button class=\"boxed-btn3 w-100\" type=\"submit\">Apply Now</button>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-lg-4\">\r\n");
      out.write("                    <div class=\"job_sumary\">\r\n");
      out.write("                        <div class=\"summery_header\">\r\n");
      out.write("                            <h3>Job Summery</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"job_content\">\r\n");
      out.write("                            <ul>\r\n");
      out.write("                                <li>Published on: <span>12 Nov, 2019</span></li>\r\n");
      out.write("                                <li>Vacancy: <span>2 Position</span></li>\r\n");
      out.write("                                <li>Salary: <span>50k - 120k/y</span></li>\r\n");
      out.write("                                <li>Location: <span>California, USA</span></li>\r\n");
      out.write("                                <li>Job Nature: <span> Full-time</span></li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"share_wrap d-flex\">\r\n");
      out.write("                        <span>Share at:</span>\r\n");
      out.write("                        <ul>\r\n");
      out.write("                            <li><a href=\"#\"> <i class=\"fa fa-facebook\"></i></a> </li>\r\n");
      out.write("                            <li><a href=\"#\"> <i class=\"fa fa-google-plus\"></i></a> </li>\r\n");
      out.write("                            <li><a href=\"#\"> <i class=\"fa fa-twitter\"></i></a> </li>\r\n");
      out.write("                            <li><a href=\"#\"> <i class=\"fa fa-envelope\"></i></a> </li>\r\n");
      out.write("                        </ul>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"job_location_wrap\">\r\n");
      out.write("                        <div class=\"job_lok_inner\">\r\n");
      out.write("                            <div id=\"map\" style=\"height: 200px;\"></div>\r\n");
      out.write("                            <script>\r\n");
      out.write("                              function initMap() {\r\n");
      out.write("                                var uluru = {lat: -25.363, lng: 131.044};\r\n");
      out.write("                                var grayStyles = [\r\n");
      out.write("                                  {\r\n");
      out.write("                                    featureType: \"all\",\r\n");
      out.write("                                    stylers: [\r\n");
      out.write("                                      { saturation: -90 },\r\n");
      out.write("                                      { lightness: 50 }\r\n");
      out.write("                                    ]\r\n");
      out.write("                                  },\r\n");
      out.write("                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}\r\n");
      out.write("                                ];\r\n");
      out.write("                                var map = new google.maps.Map(document.getElementById('map'), {\r\n");
      out.write("                                  center: {lat: -31.197, lng: 150.744},\r\n");
      out.write("                                  zoom: 9,\r\n");
      out.write("                                  styles: grayStyles,\r\n");
      out.write("                                  scrollwheel:  false\r\n");
      out.write("                                });\r\n");
      out.write("                              }\r\n");
      out.write("                              \r\n");
      out.write("                            </script>\r\n");
      out.write("                            <script src=\"https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap\"></script>\r\n");
      out.write("                            \r\n");
      out.write("                          </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("   <footer>\r\n");
      out.write("		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/bottom.jsp", out, false);
      out.write("\r\n");
      out.write("	</footer>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
