SET SERVEROUTPUT ON;

CREATE OR REPLACE PROCEDURE CHANGE_SALARY(A_EMPNO IN NUMBER, A_SALARY NUMBER DEFAULT 2000 )
AS
BEGIN
    UPDATE  EMP
    SET SAL = A_SALARY
    WHERE EMPNO = A_EMPNO;
    
    COMMIT;

EXCEPTION
    WHEN VALUE_ERROR THEN
        DBMS_OUTPUT.PUT_LINE('VALUE_ERROR => '||SQLERRM);
        NULL;
    WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('NO_DATA_FOUND => '||SQLERRM);
        ROLLBACK;
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('OTHERS => '||SQLERRM);
        ROLLBACK;
END CHANGE_SALARY;
/

EXECUTE CHANGE_SALARY(A_EMPNO => 7369, A_SALARY => 1234567);
-- 파라미터를 명시적으로 표기
-- 명시하지 않아도 됨