REM PROCEDURE 생성 : CHANGE_SALARY

CREATE OR REPLACE PROCEDURE CHANGE_SALARY(A_EMPNO IN NUMBER, A_SALARY NUMBER DEFAULT 2000 )
AS
-- DEFAULT : 값이 입력되지 않았을 때 초깃값
BEGIN
    UPDATE  EMP
    SET SAL = A_SALARY
    WHERE EMPNO = A_EMPNO;
    
    COMMIT;
END CHANGE_SALARY;
/

DESC CHANGE_SALARY
-- 파라미터 구성정보 확인

REM PROCEDURE 테스트 1

VARIABLE P_EMPNO NUMBER
VARIABLE P_SALARY NUMBER

BEGIN
    :P_EMPNO := 7369;
    :P_SALARY := 7369;
    
    CHANGE_SALARY(:P_EMPNO, :P_SALARY);
END;
/

SELECT EMPNO, SAL FROM EMP WHERE EMPNO = 7369;

REM PROCEDURE 테스트 2
EXECUTE CHANGE_SALARY(:P_EMPNO);
-- EXECUTE : STORED BLOCK에 대한 간편한 처리 (내부적으로는 BEGIN~END로 바꾸어 실행)

SELECT EMPNO, SAL FROM EMP WHERE EMPNO = 7369;

-- EXECUTE CHANGE_SALARY(:P_EMPNO,123456); --예외발생
